### ISSUE TITLE
Feature Request: Download Open API Structure

### ISSUE THREAD

**Issue by tjhunkin-inhance** [rakutentech/laravel-request-docs#10]
Would be great if the open API version of the output could be downloaded

**Comment by kevincobain2000** [comment]
Thanks for the input. It is definitely in the short roadmap. I ll keep this issue open.

**Comment by beeyev** [comment]
I support this request, this is a really important feature.

**Comment by kevincobain2000** [comment]
I ll work on it next

**Comment by kevincobain2000** [comment]
I will submit a pull req soon, this is under testing right now

**Comment by kevincobain2000** [comment]
I have added the basic support. Here https://github.com/rakutentech/laravel-request-docs/pull/63

Please try it out and let me know if there are any issues or suggestions.
Currently it can export 
- rules as description
- routes as key
- query parameters for GET and request body parameters for POST, PUT and DELETE
