### ISSUE TITLE
URL rule not supported and creating artifacts in rules section

### ISSUE THREAD

**Issue by asurcodes** [rakutentech/laravel-request-docs#101]
I have found that the `URL` validation rule is not correctly supported, maybe it'd be worth to consider it as a string to avoid pipes being added to the end of the validation rules.

![image](https://user-images.githubusercontent.com/25269358/197812189-1699576d-ffe9-487e-8431-b5ce251247f3.png)

Sample rule to replicate the issue:

```
'cookies_policy' => ['url', 'nullable'],
```

I imagine this bug is because it explodes the validation rules array by `|` and it still detects the `nullable` despite it's printed in other section of the table.

I'm willing to help with this, but I considered it sufficiently subjective to bring it up in a issue for discussion. 😄

**Comment by kevincobain2000** [comment]
Fixed in #124 (probably because not using blade no more)
