### ISSUE TITLE
Route list doesn't display correctly in Safari

### ISSUE THREAD

**Issue by abodnar** [rakutentech/laravel-request-docs#107]
Started taking a look at this for a new project and noticed that the route list does not display correctly in Safari.

<img width="891" alt="Screen Shot 2022-11-30 at 2 24 45 PM" src="https://user-images.githubusercontent.com/1891200/204901229-5db40f2b-1ece-49bc-8abd-8e600ce180de.png">

I know that a UI refresh is underway, so maybe this has already been taken care of, but wanted to make sure that checking that the UI does look correctly in Safari is considered.

Also, if there's a simple patch that could be applied to this while waiting for the UI refresh, that'd be great.

Thanks.

**Comment by kevincobain2000** [comment]
Oh. Could be done by simple patch. 
will do this week.

**Comment by kevincobain2000** [comment]
Fixed in #124
