### ISSUE TITLE
Question: How to activate SQL debugging?

### ISSUE THREAD

**Issue by markus-hsk** [rakutentech/laravel-request-docs#109]
Hi there,
i recently started using this package. It's working so far but i am unable to get the executed SQLs to be printed. Like in this issue #72 i have checked my .env-File:

```env
APP_ENV=local
APP_DEBUG=true
```

also in the /api/config/request-docs.php i have set this:

`'debug' => true,`

but sadly i dont see any SQL statements. What am i doing wrong?

I am using these versions:
```
laravel/framework                  v9.42.2
rakutentech/laravel-request-docs   1.30
```

**Comment by kevincobain2000** [comment]
I don't see anything wrong, probably headers have been over-ridden somewhere?
https://github.com/rakutentech/laravel-request-docs/blob/2ad26262a205e23a81a3fe0159bbfa72787a38cc/src/LaravelRequestDocsMiddleware.php#L16-L40

**Comment by kevincobain2000** [comment]
Make sure the config has the middleware?

https://github.com/rakutentech/laravel-request-docs/blob/2ad26262a205e23a81a3fe0159bbfa72787a38cc/src/LaravelRequestDocsServiceProvider.php#L33

https://github.com/rakutentech/laravel-request-docs/blob/2ad26262a205e23a81a3fe0159bbfa72787a38cc/config/request-docs.php#L14-L16


I should add that default middleware to the config

**Comment by kevincobain2000** [comment]
Will respond this weekend with troubleshooting steps.

**Comment by syahrul84** [comment]
I have the same problem and I've been wondering how to get this to work. I hope you can update the readme and how to set this up.

**Comment by kevincobain2000** [comment]
Thanks for the details. Will make two separate middlewares in our upcoming big release. Soon.

**Comment by markus-hsk** [comment]
Hi there, thanks for the reply. Right now i enjoy a bit of vacation. I return on January and check it out then. So long i wish you all nice holidays.

**Comment by markus-hsk** [comment]
Hi there and happy new year. I found the reason and an error

I forgot to add `\Rakutentech\LaravelRequestDocs\LaravelRequestDocsMiddleware::class` to `kernel.php`, like @syahrul84 mentioned here https://github.com/rakutentech/laravel-request-docs/issues/109#issuecomment-1363565769 

Now the middleware is called but runs into an error:

```
Method Illuminate\Http\Response::getData does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Http\\Response::getData does not exist. at C:\\wamp64\\www\\api\\vendor\\laravel\\framework\\src\\Illuminate\\Macroable\\Traits\\Macroable.php:113)
```

There is no getData method for the Response object (https://laravel.com/api/9.x/Illuminate/Http/Response.html). I tried to fix it, using `getContent()` instead of `getData()` but then the assignment of _lrd fails because the return is type string. I suggest placing the complete response in an own json that contains _lrd, memory and content as top level attributes instead of extending the given response. That would be more secure.

**Comment by kevincobain2000** [comment]
Thanks for pointing out the issue with getData. 
by own response, are you suggesting multiple json responses. In my understanding, extending the current json is the only way to attach such information.

**Comment by markus-hsk** [comment]
Ah no, i guess my suggestion is a bit misleading. 

Currently you're extending the response content with an additional attribute `_lrd`, blindly assuming the response is of type object. If its not (string p.e.) the assignment would crash.

I suggest something like this:

```php
        $original_content = $response->getOriginalContent();
        $new_content = [
            'content' => $original_content,
            'queries' => $this->queries,
            'memory'  => (string) round(memory_get_peak_usage(true) / 1048576, 2) . "MB",
        ];
```

Create a new array and add the original content as an element. Now the type and structure of the response content is irrelevant. I hope you can follow my thought. :-)

**Comment by kevincobain2000** [comment]
I got it now. Will do that.

**Comment by kevincobain2000** [comment]
Closing this issue, however added @markus-hsk 's suggestion on the middleware here #124 
That should be refactored. cc @kitloong
