### ISSUE TITLE
Commented rules are included

### ISSUE THREAD

**Issue by marensas** [rakutentech/laravel-request-docs#111]
Request form rules:
![image](https://user-images.githubusercontent.com/18376464/208441063-f7070e1d-09e2-4600-9bf8-fdba92d11f71.png)

Output after `lrd:generate` command:
![image](https://user-images.githubusercontent.com/18376464/208441176-ce545f87-662d-47f7-8330-f4a3ec7ba769.png)

**Comment by kevincobain2000** [comment]
This is fixable. Will fix.

**Comment by kevincobain2000** [comment]
Fixed in #124
