### ISSUE TITLE
The route request-docs/localhost/... could not be found.

### ISSUE THREAD

**Issue by cassiofb-dev** [rakutentech/laravel-request-docs#113]
Hi, my problem is that the right URL is displayed but not used.

![image](https://user-images.githubusercontent.com/61878987/211048656-bf480c62-c848-4643-bb1e-36255d54d4e6.png)

---

And if you open the displayed URL you will get just fine:
![image](https://user-images.githubusercontent.com/61878987/211049109-0f0f7cb6-8d81-45bf-8af9-bbe889bda0d8.png)

---

My enviroment is this image:
```Dockerfile
# syntax=docker/dockerfile:experimental

FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade

RUN apt install mysql-client openssl -y

RUN apt install php php-common php-curl php-json php-mbstring php-mysql php-xml php-zip -y

RUN apt install composer -y
```

**Comment by cassiofb-dev** [comment]
Oh, if you click on the URL displayed you will go to:
![image](https://user-images.githubusercontent.com/61878987/211049980-c4637598-1627-4d50-b115-5c934654ebf2.png)

**Comment by cassiofb-dev** [comment]
Awesome project btw!

**Comment by abodnar** [comment]
Request URL isn't bringing in the port. Just the APP_URL

**Comment by kevincobain2000** [comment]
Following is how the **REQUEST URL \*required** field value is taken Laravel -> View as below:

https://github.com/rakutentech/laravel-request-docs/blob/2ad26262a205e23a81a3fe0159bbfa72787a38cc/resources/views/index.blade.php#L595-L603

and then it is picked by the View -> JS as below:

https://github.com/rakutentech/laravel-request-docs/blob/2ad26262a205e23a81a3fe0159bbfa72787a38cc/resources/views/index.blade.php#L373-L377



>Request URL isn't bringing in the port. Just the APP_URL

Good point, make sure your **APP_URL** is in the .env (and then config) is correctly set

PS: REQUEST URL field is an editable field btw, you can edit it to the correct URL to make the request, Although it should be picking up the correct URL by default based on your APP_URL, you might want to double check that.

**Comment by kevincobain2000** [comment]
Just FYI to all,
In the new renewal (which is awesome UI btw), we will be adding a fallback as the current domain via JS, in cases where APP_URL is not set. Although, most Laravel projects have that set up.

bcc @truongns and @kitloong

**Comment by abodnar** [comment]
Yeah, I figured that was the issue and had run into this as well with running the app in Laravel Sail.

At first I was going to suggest looking if the APP_PORT(Sail has you use this to change the port the app is available on) env was set, but as I think about it, I'm kind of surprised that config('app.url') doesn't take into account APP_PORT.

Either way, it's an easy enough fix.

Side note, any screenshots or place we can see the new UI? @kevincobain2000

**Comment by kevincobain2000** [comment]
I have set my APP_URL with the port as `APP_URL=http://localhost:8000` and it picks up just fine.

About the screenshot, I'd have to say please wait a little more but it includes the libraries: daisyui, dark mode, monaco-editor, font changes, postman-styled query params (with JSON editable body), save the query params in browser for the user, etc etc.
We should be able to release it in a couple more weeks.

**Comment by cassiofb-dev** [comment]
> I have set my APP_URL in local with the port as `APP_URL=http://localhost:8000` and it picks up just fine.
> 
> About the screenshot, I'd have to say please wait a little more but it includes the libraries: daisyui, dark mode, monaco-editor, font changes, postman-styled query params (with JSON editable body), save the query params in browser for the user, etc etc. We should be able to release it in a couple more weeks.

I have this setup, just not with the port. I'm going to check it.

**Comment by abodnar** [comment]
> I have set my APP_URL in local with the port as `APP_URL=http://localhost:8000` and it picks up just fine.
> 
> About the screenshot, I'd have to say please wait a little more but it includes the libraries: daisyui, dark mode, monaco-editor, font changes, postman-styled query params (with JSON editable body), save the query params in browser for the user, etc etc. We should be able to release it in a couple more weeks.

Adding the port to APP_URL worked for me as well.

Sounds good. Appreciate it.

**Comment by cassiofb-dev** [comment]
> > I have set my APP_URL in local with the port as `APP_URL=http://localhost:8000` and it picks up just fine.
> > About the screenshot, I'd have to say please wait a little more but it includes the libraries: daisyui, dark mode, monaco-editor, font changes, postman-styled query params (with JSON editable body), save the query params in browser for the user, etc etc. We should be able to release it in a couple more weeks.
> 
> Adding the port to APP_URL worked for me as well.
> 
> Sounds good. Appreciate it.

Mine env var was setup too (tried with and without port), I didn't try to run locally though. Maybe it was docker issue, I'll check it without the container later 🤔

**Comment by kevincobain2000** [comment]
Cool. Looks like all good then. I ll close this issue. よろしく

**Comment by cassiofb-dev** [comment]
@kevincobain2000 sorry, the issue was me. I found it will not work with:

1. If you don't put ``http://`` in the beginning (only ``localhost:8000`` will not do)
2. If you open the backend with the address below it will not work (even though the app works fine):
  - ``http://127.0.0.1:8000/request-docs``
  - ``http://0.0.0.0:8000/request-docs``
3. You must open in the same address to avoid CORS error (in my case was ``http://localhost:8000/request-docs``)

Welp, thanks for the quick answers and hope you guys can go on with the project! I'll put a print of it working, awesome tool!

![image](https://user-images.githubusercontent.com/61878987/211377194-0d8c3dac-f74e-469e-8c48-ada10aa4f640.png)

**Comment by kevincobain2000** [comment]
Thanks for the confirmation.
