### ISSUE TITLE
Attributes Request not show when use isMethod condition

### ISSUE THREAD

**Issue by paul-lestyo** [rakutentech/laravel-request-docs#114]
hi, I'm new here 
when I try to use isMethod condition in Request Class, the documentation does't show like below.

my request
![image](https://user-images.githubusercontent.com/51690314/213130416-b85e794e-ca76-4eb5-8118-e2f625968713.png)

documentation
![image](https://user-images.githubusercontent.com/51690314/213130628-694465ac-13a7-4ee0-b004-f6097815ed2f.png)

is there any solution regarding this? thx

**Comment by kevincobain2000** [comment]
The solution to fix this is to not use the same request class for 2 different API routes/methods.
One of the motivations to develop this LRD was to actually identify bad design patterns that can lead to spaghetti.

My suggestion is that you could choose to use inheritance and that would make your code much cleaner and more scalable.

**Comment by paul-lestyo** [comment]
@kevincobain2000 OK thanks for the advice. I will consider separating the classes for the different methods and I can't wait for the new update from this package.
