### ISSUE TITLE
Is there a way to not show Controller Method and Middleware ?

### ISSUE THREAD

**Issue by ghost** [rakutentech/laravel-request-docs#119]
Is there a way to not show Controller Method and Middleware, we don't need that in our project

**Comment by kevincobain2000** [comment]
right now there is no way, but can be added as a feature in the upcoming release

**Comment by niteshs-reconnectin** [comment]
oh thanks

**Comment by kevincobain2000** [comment]
Thanks. There is a nextjs issue on export that is causing a delay. Hope is to release within feb.

**Comment by kevincobain2000** [comment]
Fixed in #124 via `config('request-docs.hide_meta_data')`
