### ISSUE TITLE
Enums array to string not resolving in docs

### ISSUE THREAD

**Issue by jackkitley** [rakutentech/laravel-request-docs#120]
We have enums to string as suggested rules for the request but it doesnt seem to resolve when generating api docs.

This used to work in older versions of laravel-request-docs

**Comment by jackkitley** [comment]
![Screenshot 2023-02-08 at 15 22 14](https://user-images.githubusercontent.com/3243014/217542284-7ccaaa78-c7de-4470-bb4b-1d7326b6c6ce.jpg)

**Comment by kevincobain2000** [comment]
Similar #80 
Unable to fix and can't fix. Sorry.

**Comment by kevincobain2000** [comment]
ok so enums are normally supported.

But because the rule in the screenshot has `$this->input('lead.dealership_id'`, the reflection class fails to obtain the inherited methods, it fails and falls back to regexp matching.

This is the root cause.

cc @kitloong 

--
Not sure what can be done here.

**Comment by kevincobain2000** [comment]
Actually this https://github.com/rakutentech/laravel-request-docs/pull/84/files

The following may fix the issue

```
                    // $requestClass = $reflection->newInstanceWithoutConstructor();
                    $requestClass = $reflection->newInstance();
```

**Comment by kevincobain2000** [comment]
Fixed
