### ISSUE TITLE
URL request

### ISSUE THREAD

**Issue by SilvaEngComp** [rakutentech/laravel-request-docs#122]
Hi I'd like be able to define base URL. I'd like to be able to make my documentation available to my QAs and it easy to test in production test envirionment.  So in this part of the request-docs does it's possible to make a flex definition of URL like below?

  /*
    * Route where request docs will be served from
    * localhost:8080/request-docs
    */
    'url' => env('LDR_APP_URL', 'LDR_APP_URL_PROD'),

Kind regards...

**Comment by kevincobain2000** [comment]
It is possible via config
https://github.com/rakutentech/laravel-request-docs/blob/1795a671ea9cfb79934b6dc054f05d1ef4dafa3b/config/request-docs.php#L13

**Comment by SilvaEngComp** [comment]
Hi! Thank you for answare me! 
To description part It is ok, but to Try button It is not working 
ex:  if I do this 
'url' =>'http://localhost:8000/api',

show for me some like this 

![image](https://user-images.githubusercontent.com/11936035/220201400-a00db5c4-4e26-4196-923b-ffa8eef60008.png)

**Comment by kevincobain2000** [comment]
Please update to v2
