### ISSUE TITLE
When unpkg.com is down, documentation doesnt load

### ISSUE THREAD

**Issue by qwasyx0** [rakutentech/laravel-request-docs#123]
Right now https://www.unpkg.com/status/ returns 502 as well as 
- vue-prism-editor
- string-similarity.min.js
- vue-markdown.js

Maybe switch to different provider, eg jsdelivr (which you use for example for vue)?

**Comment by kevincobain2000** [comment]
Will be fixed this Sunday.

**Comment by kevincobain2000** [comment]
Releasing new docs that bundles js and won’t call 3rd party urls this week

**Comment by kevincobain2000** [comment]
Fixed in #124
