### ISSUE TITLE
CSRF token mismatch laravel message (Response 419)

### ISSUE THREAD

**Issue by danielhr2001** [rakutentech/laravel-request-docs#131]
I tested this package on my laptop-127.0.0.1:8000-windows11 by "php artisan serve".  
1- and I changed the default value of APP_URL to http://127.0.0.1:8000 on the .env file.
2- then I opened http://127.0.0.1:8000/request-docs and test my restfull-api-routes.
3- but I took a CSRF Error.
4- I tested it on some other routes that are protected by policy-classes (and I didn't set any bearer token) and I took 403. (that means it can work until policies) but somewhere after policy It has a problem and gives me CSRF Error for other routes when It passed policy.

**Comment by danielhr2001** [comment]
oh It fixed by this solution:
```
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array<int, string>
     */
    protected $except = [
        '/api/*'
    ];
}
```
I added api-routes on CSRF-Exception!. but I think it's not a safe solution.

**Comment by kevincobain2000** [comment]
Apis don’t need a csrf. They can work on cors and application/json headers to be safe.

**Comment by kevincobain2000** [comment]
However I ll add csrf in header back if enough ppl have the same settings.

**Comment by itwondersteam** [comment]
@kevincobain2000 We are using web session, thus would need the CSRF header. Is it possible to enable CSRF via the config?
