### ISSUE TITLE
Laravel 10 error

### ISSUE THREAD

**Issue by Lashalilu** [rakutentech/laravel-request-docs#132]
When I installed package on latest version of Laravel (10), I got the white page without any result. Sometimes I got the view but not the endpoints. Please take a look.

**Comment by kevincobain2000** [comment]
Thanks for reporting.
What do have for the following?

1.  yoururl/request-docs/api
2. And any console logs on the browser?

Probably missing `php artisan route:cache`

**Comment by kevincobain2000** [comment]
one more thing.
Sorry it was not clear in the README's change log, since it is new vup please don't forget to republish the config file

```
php artisan vendor:publish --tag=request-docs-config
php artisan route:cache
php artisan config:cache
```

**Comment by kevincobain2000** [comment]
let me know if that fixes your issue @Lashalilu 
Feel free to reopen
