### ISSUE TITLE
error TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [rakutentech/laravel-request-docs#137]
Thanks for this amazing library 
![chrome-capture-2023-1-23](https://user-images.githubusercontent.com/17373050/220931284-605bc4c3-7b91-40d6-b16b-5c835d091f1d.gif)

I got this error in the browser 

TypeError: Cannot read properties of undefined (reading 'map')
    at Mm (App.f7973191.js:1185:1252)
    at lu (client.8c8eb78c.js:22:19476)
    at Ca (client.8c8eb78c.js:24:43678)
    at ka (client.8c8eb78c.js:24:39483)
    at Ef (client.8c8eb78c.js:24:39414)
    at Qr (client.8c8eb78c.js:24:39274)
    at zi (client.8c8eb78c.js:24:35696)
    at ya (client.8c8eb78c.js:24:34652)
    at E (client.8c8eb78c.js:9:1562)
    at MessagePort.lt (client.8c8eb78c.js:9:1930)
vi @ client.8c8eb78c.js:24
client.8c8eb78c.js:24

**Comment by kevincobain2000** [comment]
Thanks for reporting. 
Will reply tomorrow morning. 
meanwhile make sure you have not forgotten route:cache and config:cache

**Comment by kevincobain2000** [comment]
What do have for the following?

- localhost:8000/request-docs/api
- And any console logs on the browser?

And please verify the following steps have been done

```
php artisan vendor:publish --tag=request-docs-config
php artisan route:cache
php artisan config:cache
```

**Comment by kevincobain2000** [comment]
Hi, any updates on this?
Feel free to re-open if issues after republishing config and configuring cache.

**Comment by Marchiuzzz** [comment]
Having the same issue, did all of the following, still same issue:
```
php artisan vendor:publish --tag=request-docs-config
php artisan route:cache
php artisan config:cache
```

**Comment by kevincobain2000** [comment]
What is the output from `localhost:8000/request-docs/api`?

**Comment by kevincobain2000** [comment]
Also please check that your public vendors dir must be empty. The new version doesn't need anything published

```
╰─$ ls -l public/vendor/request-docs
ls: public/vendor/request-docs: No such file or directory
```

**Comment by Marchiuzzz** [comment]
I've enabled debugging in the config and inspected the error. It seems this tool fails when there's a route that uses a function that doesn't actually exist in the controller. I know overall this shouldn't happen, we shouldn't have such routes but I installed this on an old project and it seems to have a few of such routes. Once I removed those routes it started working.

**Comment by kevincobain2000** [comment]
oh got it.
Generally the debug of config('request-docs.debug')` needs to be false.
That is only added to find out for what routes LRD is unable to get the information from. Mostly for CI to keep a check on the developers following right coding practices for requests.

**Comment by kevincobain2000** [comment]
However, now I see the issue, I ll add better error message on the UI for such cases.

**Comment by kevincobain2000** [comment]
Added to an issue, will close this.
Thanks for notifying!
