### ISSUE TITLE
Group by including unrelated api routes

### ISSUE THREAD

**Issue by ravnsborg** [rakutentech/laravel-request-docs#143]
routes displayed inside unrelated routes section.

![groupby](https://user-images.githubusercontent.com/4323866/221300669-169414a1-83b8-4038-a7cd-3bfb5376311d.png)

**Comment by kevincobain2000** [comment]
Thanks for reporting. Should be a quick fix. 
assigned to @kitloong

**Comment by kevincobain2000** [comment]
Will be fixed after UT fix https://github.com/rakutentech/laravel-request-docs/pull/148#discussion_r1117908603

**Comment by kevincobain2000** [comment]
Fixed!!!
