### ISSUE TITLE
confirmed rule didnt add password_confirmation key in request automatically.

### ISSUE THREAD

**Issue by web95-moon** [rakutentech/laravel-request-docs#157]
Hi

Is there any way to automatically get the password_confirmation key in a request when using a confirmed rule in laravel.

By the way great work on this open-source package.

![Screenshot 2023-02-27 124205](https://user-images.githubusercontent.com/125456979/221497827-71860ba8-0731-469d-864f-e9540fcc8255.png)

**Comment by kevincobain2000** [comment]
Noted thanks! Will add that next.

**Comment by kevincobain2000** [comment]
Forwarded to @kitloong 
Probably you can also append that on the backend, frontend can display without changes.

**Comment by kevincobain2000** [comment]
I looked into it, but it is better to specifically provide extra rule as below in order to prevent magic.

```
'password' => 'required|min:6|confirmed',
'password_confirmation' => 'required|min:6'
```
