### ISSUE TITLE
[Question] Is it possible to somehow document params of GET route without using custom request class?

### ISSUE THREAD

**Issue by Marchiuzzz** [rakutentech/laravel-request-docs#159]
Basic example - let's say I have a GET route `/api/product/{id}`
And the function is something like:
```
public function show($id){
 return new ProductResource(Product::findOrFail($id));
}
```
My question is, do I need to rework this so that the function is something like this?:
```
public function show(ShowProductRequest $request){
 return new ProductResource(Product::findOrFail($request->id));
}
```

Or is there a way to cover such cases out of the box?

**Comment by kevincobain2000** [comment]
This is correct.

```
public function show($id){
 return new ProductResource(Product::findOrFail($id));
}
```
You can provide `{id}` in the URI section, which is an editable field as below:


![Screen Shot 2023-02-27 at 18 31 27](https://user-images.githubusercontent.com/629055/221526416-608c972c-f2e6-4b02-9db4-1e868d6b552c.png)




If I have to refactor your code I'd be doing like below

```
public function show(ShowProductRequest $request, $id){
 return new ProductResource(Product::findOrFail($id));
}
```

**Comment by Marchiuzzz** [comment]
So there's no way to say that $id is required and must be of type integer if I use `function show($id)`?

Also, if I refactor it to be 
```
public function show(ShowProductRequest $request, $id){
 return new ProductResource(Product::findOrFail($id));
}
```
Do I then just add rules for id field inside `ShowProductRequest` class even though it is not actually used?

**Comment by kevincobain2000** [comment]
It is more like known that id is a default must. Otherwise your request will go to a different route and controller. Just presence is {id} in the route is self explanatory. 
I could however add type.

**Comment by Marchiuzzz** [comment]
Okay, thanks for clarifying
