### ISSUE TITLE
api documentations not working for xampp users

### ISSUE THREAD

**Issue by web95-moon** [rakutentech/laravel-request-docs#164]
consider below envoirnment

install xampp
change the directory to c:/xampp/htdocs and execute the below command to install the new project with the composer.
composer create-project laravel/laravel test-project-1
update .env database credentials
create some API
execute the below commands to install the package.
composer require rakutentech/laravel-request-docs --dev
php artisan vendor:publish --tag=request-docs-config
php artisan route:cache

now run project with below url it will not work and just show 1.
http://localhost/test-project-1/public/request-docs

Note:- it's working with php artisan serve
Expected behavior:- should work with any environment.

let me know if I can provide more details.

![image](https://user-images.githubusercontent.com/125456979/221799513-4889bb60-8483-4843-8c0d-02315c057235.png)

**Comment by kevincobain2000** [comment]
Thanks for reporting. I ll check this.

**Comment by kevincobain2000** [comment]
Why does the URL have a `/public/` in it?
How about `localhost/request-docs`?

**Comment by web95-moon** [comment]
i believe it because of index.php file in public directory with default project installation and entry point of laravel project is on index.php file

below is the .htaccess file which comes with the default installation.

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Send Requests To Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

**Comment by web95-moon** [comment]
with xampp we cannot run the project with just localhost

we must give a project directory name from htdocs folder follow by /public like

http://localhost/test-project-1/public/

![image](https://user-images.githubusercontent.com/125456979/221826040-3b694be4-292f-4c29-ac3f-a5f1cb744a91.png)

**Comment by kevincobain2000** [comment]
There are 2 things I suspect that are messing up the paths

1) https://github.com/rakutentech/laravel-request-docs/blob/031b1a43105dcc65ab328d4e31910f88a2df54b1/resources/views/index.blade.php#L1

2) https://github.com/rakutentech/laravel-request-docs/blob/031b1a43105dcc65ab328d4e31910f88a2df54b1/config/request-docs.php#L12

Probably try changing the base path there to `/public/request-docs`, then `route:cache, config:cache`

--

If still not so, then I ll try it out on my MAMP, I don't have windows, so kinda will need more of your help than mine.

**Comment by web95-moon** [comment]
config\request-docs.php
changed the 'URL' value to  'public/request docs' and also tried with '/public/request docs',
and now I need to access the request-docs route through 'http://localhost/test-project-1/public/public/request-docs' URL else getting a 404 error. and yet the result is the same.

![image](https://user-images.githubusercontent.com/125456979/221850336-7d6b7b5e-8ea2-49cc-9185-fb3dab8b4027.png)

**Comment by kevincobain2000** [comment]
okay got it, so the assets are not respecting the base path.
Actually nothing can be done in this case I am afraid. You have to get rid of the base path `/public`.
You project must be served without a base path `http://localhost/` where the root is.

Or if you can make the [`dist`](https://github.com/rakutentech/laravel-request-docs/tree/master/resources/dist) files available at your `localhost/request-docs/` manually.

The reason is that this package is provided as static file and base path is set and cannot be changed on the dist.

**Comment by kevincobain2000** [comment]
Just one more info, if you want to publish the dist yourself and serve them from a different folder/path/cdn. 
You can do that as follows

1. `cd vendor/rakutentech/laravel-request-docs/ui`
2. `vi astro.config.mjs`
3. Change the path and out dir https://github.com/rakutentech/laravel-request-docs/blob/master/ui/astro.config.mjs#L18-L19
4. `npm install && npm export`

**Comment by web95-moon** [comment]
Sure i will check and apply above solutions Thanks.

**Comment by web95-moon** [comment]
One more issue right now I am running a project through php artisan serve now API documentation is generated and it's showing requests and their validations but parameter keys are not added automatically what can cause this issue or how can i solve this?

below is configurations 
config\request-docs.php
'only_route_uri_start_with' => 'api',
'url' => 'request-docs',
'open_api' => [
'server_url' => env('APP_URL', 'http://localhost'),
]

.env
APP_URL=http://localhost

**Comment by kevincobain2000** [comment]
Interesting.
It should have been there. I have no issues on mine. 
can you update to the latest version. 
And and click settings on top nav and clear local storage. 

Note: the request body and params that you input are stored in the local storage, so if you ever cleared the request body in the past, it would have stated that ways.

**Comment by web95-moon** [comment]
clearing local storage worked many thanks.

**Comment by kevincobain2000** [comment]
I ll update in next version to revert back to auto fill default params when the local storage has empty body.

**Comment by kevincobain2000** [comment]
created issue above
