### ISSUE TITLE
Response error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by tolgacibikci** [rakutentech/laravel-request-docs#166]
Hi, first of all apologies for my bad english.

I am using laravel sanctum. When I send a request to the   'api/register' end point, "CSRF token mismatch." I get an error.

![Ekran Resmi 2023-03-01 16 41 14](https://user-images.githubusercontent.com/48218558/222155471-d7492908-78ee-4264-aee6-a168bb1f6c8b.png)

![Ekran Resmi 2023-03-01 16 41 26](https://user-images.githubusercontent.com/48218558/222155578-c2f9aa70-ee75-4c7e-ae13-a93fb0284a3e.png)

To get CSRF tokens, I send a request to the 'sanctum/csrf-cookie' end point. In response, I get the error 'Response error: SyntaxError: Unexpected end of JSON input'.

What am I doing wrong?

![Ekran Resmi 2023-03-01 15 39 37](https://user-images.githubusercontent.com/48218558/222155670-b6711b40-7ab8-4248-be10-76edc55c95d0.png)

![Ekran Resmi 2023-03-01 15 40 12](https://user-images.githubusercontent.com/48218558/222155719-d07e9ca5-c083-421e-b93f-5ea19317a80a.png)

PHP: v8.2.3
Laravel: v10.1.5
Sanctum: v3.2.1
laravel-request-docs: v2.8

Secondly, can we write Pre-request Script or Test Script as in postman?

**Comment by kevincobain2000** [comment]
I have found the issue, I think this was not supported in previous version 1.x as well.
I ll push the support today.

**Comment by kevincobain2000** [comment]
Should be fixed in 2.9, please update.
Please reopen this if it doesn't fix your issue
