### ISSUE TITLE
validations rules info not displaying when password (Illuminate\Validation\Rules\Password) class used 

### ISSUE THREAD

**Issue by web95-moon** [rakutentech/laravel-request-docs#180]
![image](https://user-images.githubusercontent.com/125456979/223075505-2d7e76bd-6345-4254-9adf-52b869b3ede9.png)
![image](https://user-images.githubusercontent.com/125456979/223075571-e5a6268a-6164-4860-935a-ae3c1f203e7d.png)

https://laravel.com/docs/10.x/validation#validating-passwords

Also keep in mind of displaying validation rule info with below 

https://laravel.com/docs/10.x/validation#defining-default-password-rules

**Comment by kevincobain2000** [comment]
Yes. This is not parsed and there is no other way yet to parse info from classes.
