### ISSUE TITLE
Change title and description

### ISSUE THREAD

**Issue by Julien-cpsn** [rakutentech/laravel-request-docs#195]
Hello !

It would be great as previously possible to change the API title and description in the config file :)

https://github.com/rakutentech/laravel-request-docs/blob/63511df8c01deb6946d2ca0581c0169ea96f46f0/src/LaravelRequestDocsToOpenApi.php#L17
https://github.com/rakutentech/laravel-request-docs/blob/63511df8c01deb6946d2ca0581c0169ea96f46f0/src/LaravelRequestDocsToOpenApi.php#L18

**Comment by kevincobain2000** [comment]
Okay :)

**Comment by kevincobain2000** [comment]
No body gave a pull req. Closing it.
