### ISSUE TITLE
[Path Item Object] "in": "path" management

### ISSUE THREAD

**Issue by Julien-cpsn** [rakutentech/laravel-request-docs#196]
Hi again!

## Problem

Getting through the code I found that the lib isn't taking part of the `"in": "path"` specification (aka Path Item Object) of the OpenAPI Specifications.
Such as follow :
https://swagger.io/specification/v3/#path-item-object

Making it available in the lib would be great! At least for Open API please, so that we can use routes like `/users/{id}/remove` .

## An idea for minimal avaibility
I think that changing this line
https://github.com/rakutentech/laravel-request-docs/blob/63511df8c01deb6946d2ca0581c0169ea96f46f0/src/LaravelRequestDocsToOpenApi.php#L94 

To :
```php
'in'    => str_contains($rule, 'path') ? 'path':'query',
```
Would be a great way to start.
I tried to code it like the way you managed the `required` parameter

**Comment by kevincobain2000** [comment]
Fwd to @kitloong

**Comment by kevincobain2000** [comment]
Related #162

**Comment by kevincobain2000** [comment]
Thanks I think it is work in progress by @kitloong

**Comment by kevincobain2000** [comment]
Ref: #198
