### ISSUE TITLE
Rules with parameters

### ISSUE THREAD

**Issue by guille1988** [rakutentech/laravel-request-docs#197]
Good morning. Thank u in advance for making this package, it's really cool and congratulations for the effort of making it.
I have a bug in the package I think, when I put a rule with parameters, the package doesn't detect any field. It's like it can't recognize nothing. Here's an example:

```
public function rules(): array
    {
        $email = ['required', 'string', 'exists:users,email'];
        $hash = ['required', 'string', new InvalidHash(email: $this->email)];

        return compact(['email', 'hash']);
    }
```

Thank u, Guillermo.

**Comment by kevincobain2000** [comment]
Thanks and yes it doesn't and it is not possible at this moment.
