### ISSUE TITLE
News suggestions from Povilas Korop

### ISSUE THREAD

**Issue by rafgirao** [rakutentech/laravel-request-docs#20]
Please take a look at this video: https://www.youtube.com/watch?v=gp-_kcblYGA

**Comment by kevincobain2000** [comment]
Thank you all for reporting and sharing the details.
Special thanks to @PovilasKorop

I was able to fix quite many issues in last month
Change log is here: https://github.com/rakutentech/laravel-request-docs/blob/master/README.md#changelog
