### ISSUE TITLE
Option to only show a class' short name instead of the full namespace and class

### ISSUE THREAD

**Issue by abodnar** [rakutentech/laravel-request-docs#203]
**Is your feature request related to a problem? Please describe.**
While recently setting up a new endpoint, I added a rule that uses a model to have it check that the name provided is unique in the table. Now one way to do this is to put `Model::class` instead of the actual table name as this allows it to automatically point to the correct table if that ever changed. Eg, `'name' => 'required|unique:'.Role::class.',name|max:255',`

When you go to look at the endpoint LRD, this renders as `unique:Silber\Bouncer\Database\Role,name | max:255` and while not horrible, it'd be nice if that full namespace wasn't shown.

**Describe the solution you'd like**
Instead of it showing `unique:Silber\Bouncer\Database\Role,name | max:255`, it would show as `unique:Role, name | max:255`

**Describe alternatives you've considered**
Using the table name instead of the class name

**Comment by kevincobain2000** [comment]
Doable, will reply soon after today’s baseball game.

**Comment by kevincobain2000** [comment]
ok this is possible, but do you **really** need this?
I could add it to settings as "Display options: short|long" or something and do everything on the frontend.

**Comment by abodnar** [comment]
It would be beneficial as our api documentation will be available to 3rd party clients and there is no benefit for them to see the full class name in it.

Doing it on the frontend is not the most ideal, but at least it'd give an option that I could work with.

**Comment by kevincobain2000** [comment]
I also thought at first to do it on backend. I agree that doing it on front end is not ideal. 
Just didn’t feel like cluttering the config file. 

haven’t started on it yet so we can still decide

**Comment by kevincobain2000** [comment]
Feel free to reopen with a pull req.
