### ISSUE TITLE
Is there a way to specify response data?

### ISSUE THREAD

**Issue by alierdem** [rakutentech/laravel-request-docs#208]
i dug through documentation but cant find anything. is there a way to specify what a response would return ? 
for example: in the get methods i want to specify a schema

**Comment by kevincobain2000** [comment]
Response schema suppport currently cannot be specified.

**Comment by alierdem** [comment]
> Response schema suppport currently cannot be specified.

i want to implement this. where should i start ? i never used the reflection before and got a little bit lost in the source

**Comment by kevincobain2000** [comment]
Thanks
@alierdem 
You can look into this class, and if you can get the return type `Resource` from the controller's method and convert it somehow to a response schema. 

If you can append it on the backend, for the frontend I can handle the display of it.

https://github.com/rakutentech/laravel-request-docs/blob/a0279379e3c8f81685ec11f7e78e09d749a329d0/src/LaravelRequestDocs.php#L189


cc @kitloong

**Comment by kevincobain2000** [comment]
Partially fixed by #212
