### ISSUE TITLE
Publishing the docs

### ISSUE THREAD

**Issue by cleitokarloh** [rakutentech/laravel-request-docs#210]
Hello, have a way to generate static files to publish in github-pages?

**Comment by kevincobain2000** [comment]
Yes there is one option but I haven’t enabled and tested it yet. Will enable after April 20th

**Comment by kevincobain2000** [comment]
Idea is to be able to remove `client:only` somehow using `sed` or `index.ssr.astro`, and then run `npm run export --destination=`
This will export entire routes for the project as static...

https://github.com/rakutentech/laravel-request-docs/blob/a0279379e3c8f81685ec11f7e78e09d749a329d0/ui/src/pages/index.astro#L16

Things need to be done are:
- Update index.astro
- Update dst dir via cli params

**Comment by rabie707** [comment]
Hey, really love this package, regarding the generate docs feature, is this enabled now ?, or how can we export the generated results to pdf at least
Thanks.

**Comment by kevincobain2000** [comment]
PDF not possible
HTML (gh-pages) is possible, I haven't started the implement yet.
I am planning to do some implementations by the end of this month.

**Comment by rabie707** [comment]
okay, my solution to this might be a bit primitive then, i'm thinking about adding some css classes overrides using the @media print annotation, to make the browser's "Print as PDF" option more viable,
thanks for the efforts tho

**Comment by kevincobain2000** [comment]
That could be possible, but I think it would be too ugly PDF and may require a lot of css bandages.
I have never hit the CMD+P tho, so I ll try it out and see if it is worth the effort.

**Comment by kevincobain2000** [comment]
Feature to export directly from a project is kinda tedious and risky in a way, therefore instead:

For now, if you really need it, then you can choose to do something like below:

**CASE with CORS**

1. Make the output from your app for the LRD api, public and CORS enabled for `.github.io`.

2. Then access as

```
// directly
https://rakutentech.github.io/laravel-request-docs/?api=<YOUR-URL/request-docs/api>
```

**Case without CORS**

_If you choose to publish it on public Github or Gist, then CORS are not required, see SAMPLE below._

```
// copy <YOUR-URL/request-docs/api> to output.json and paste it to Github or GIST
https://rakutentech.github.io/laravel-request-docs/?api=<RAW-GITHUB-URL/output.json>

```

[SAMPLE](https://rakutentech.github.io/laravel-request-docs/?api=https://raw.githubusercontent.com/rakutentech/laravel-request-docs/master/ui/public/sample.json)
