### ISSUE TITLE
The URL bar is not updating

### ISSUE THREAD

**Issue by mohhamedion** [rakutentech/laravel-request-docs#211]
when i click on API link, the URL bar should update the request to something like 
```request-docs#GETapi/languages/get-language```
so i can copy the link and share it 

But this is not happening
Thank you.

**Comment by kevincobain2000** [comment]
Thanks. This needs to be fixed. I ll fix it this week.

**Comment by mohhamedion** [comment]
Thank you. waiting :+1:  :smile:

**Comment by kevincobain2000** [comment]
Fixed
