### ISSUE TITLE
Markdown indentation not being taken 

### ISSUE THREAD

**Issue by Franpanozzo** [rakutentech/laravel-request-docs#212]
Hi there! hope you're doing great. Here's the thing, I want to have identation on my extra documentation for the endpoints (the main goal behind this is that we want to add the form of the response body, since this package doesn't read the Resources).

    /**
     * @lrd:start
     * Data on success:
     * ```
        {
            "data": [
                {
                    "id": 16,
                    "year": 2019,
                    "company_id": 2,
                    "user_id": 2,
                    "industry_id": 2,
                    "E_score": null,
                    "S_score": null,
                    "G_score": null,
                    "overall_score": null,
                    "closing_date": null,
                    "is_annual": true
                }
            ]
        }
     * ```
     * @lrd:end
     *
     * @throws Exception
     */

    public function start(StartReportRequest $request): JsonResponse
    {

 
 But in the HTML of the documentation, the indentation doesn't work:
 
![image](https://user-images.githubusercontent.com/62455934/232471171-497f421c-1f51-4c23-a797-574872fd3204.png)

If you guys could give me a hand with this one it will be great. Thanks in advance!

**Comment by kevincobain2000** [comment]
Fixed
