### ISSUE TITLE
Laravel Module

### ISSUE THREAD

**Issue by zkenstein** [rakutentech/laravel-request-docs#214]
Please add compatible with Laravel NwiDart module

**Comment by kevincobain2000** [comment]
Thanks
I have never used NwiDart. Is it completely not compatible right now?
What exactly are compatibility issues with it right now?

**Comment by xetova-technology** [comment]
it generates the docs. i have tried it

**Comment by kevincobain2000** [comment]
Thanks @xetova-technology 
So no problem @zkenstein, can you please test it.
It should be generating the docs as usual I believe.
