### ISSUE TITLE
ERROR  There are no commands defined in the "lrd" namespace.

### ISSUE THREAD

**Issue by xetova-technology** [rakutentech/laravel-request-docs#218]
**Describe the bug**
   ![image](https://user-images.githubusercontent.com/87365741/233823603-e82514cc-cb7e-4c74-ac27-76d39c322dee.png)

**To Reproduce**
1. `composer create-project laravel/laravel:^9 laravel`
2. `composer require rakutentech/laravel-request-docs`
3. `php artisan serve`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac] win
 - Browser [e.g. chrome, safari] edge
 

**Versions (please complete the following information):**
- Laravel Version: 9.19
- PHP Version: 8.1
- Laravel Request Docs Version:

**Additional context**

**Comment by kevincobain2000** [comment]
lrd:generate is not longer in v2.
