### ISSUE TITLE
docs page returns 1, fails to load js and css

### ISSUE THREAD

**Issue by xetova-technology** [rakutentech/laravel-request-docs#219]
![image](https://user-images.githubusercontent.com/87365741/233857329-cb0662a2-9a46-493e-bd82-01f3c55ba6ae.png)

UI returns 1 and fails to render the page

API path returns json/array as expected

setup 

nginx
php 8.1
laravel 9
laravel-request-docs v 2.15

**Comment by xetova-technology** [comment]
![image](https://user-images.githubusercontent.com/87365741/233857658-f13f5abb-06cf-4624-a001-f02a2d965874.png)

on localhost (artisan serve) it works just fine

**Comment by kevincobain2000** [comment]
Can you please check if the routes are registered for your app on that env?

```
╰─$ php artisan route:list | grep request-docs                                                                                     1 ↵
  GET|HEAD  request-docs ......... request-docs.index › Rakutentech\LaravelRequestDocs\Controllers\LaravelRequestDocsController@index
  GET|HEAD  request-docs/_astro/{slug} request-docs.assets › Rakutentech\LaravelRequestDocs\Controllers\LaravelRequestDocsController…
  GET|HEAD  request-docs/api ......... request-docs.api › Rakutentech\LaravelRequestDocs\Controllers\LaravelRequestDocsController@api
```

Thanks

**Comment by kevincobain2000** [comment]
Closing as no response

**Comment by xetova-technology** [comment]
![image](https://user-images.githubusercontent.com/87365741/235141821-783e5150-ef0b-4fc6-8c87-68b0c58bd8be.png)

**Comment by shimprog** [comment]
What was the problem? I faced the same problem

**Comment by kevincobain2000** [comment]
@shimprog https://github.com/rakutentech/laravel-request-docs/issues/234#issuecomment-1573436230
