### ISSUE TITLE
[BUG] Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by mdoulabi1** [rakutentech/laravel-request-docs#228]
Hi
when i enter http://127.0.0.1:8001/request-docs i got this error:
**Unexpected token '<', "<!DOCTYPE "... is not valid JSON**
i enable debug in config file to trace the error but it show nothing
how can i fix it?
![image](https://user-images.githubusercontent.com/59202978/236600933-bac1acac-74e3-4e4f-8b49-2d0fd688c1e6.png)
php version:8.1
laravel version :8.12

**Comment by kevincobain2000** [comment]
https://github.com/rakutentech/laravel-request-docs/issues/209#issuecomment-1499206384

Let me know the output of the /request-docs/api

**Comment by mdoulabi1** [comment]
i found the bug
when you have a route without methods or an duplicate route you get this error
in my case i have 4 routes without method in  controllers
tnx.
