### ISSUE TITLE
The application returns a 1 if the request-docs is not in root.

### ISSUE THREAD

**Issue by LordSergio** [rakutentech/laravel-request-docs#229]
If you have Laravel in another path that is not root, for example, https://my-web.com/api, the files (js, css, etc) used by the request-docs return a 404 since it looks for them in root .
This happens on a server with Vue in / and laravel in /api/

It should work whether it's in root or in another path, either via a conf parameter or automatically.

![Error](https://github.com/rakutentech/laravel-request-docs/assets/38973929/77cc163f-b2e2-4d64-99de-769b79ce3056)

- OS: Debian
 - Browser: Chrome
- Laravel Version: 9/10
- PHP Version: 8.1/8.2
- Laravel Request Docs Version: 2.16

**Comment by dmitryvasilevskiy** [comment]
same error

**Comment by kevincobain2000** [comment]
Try updating base path here 

https://github.com/rakutentech/laravel-request-docs/blob/master/config/request-docs.php#L13

**Comment by LordSergio** [comment]
Changing the 'url' parameter changes the path, but not the resources (css, js, etc)

![1](https://github.com/rakutentech/laravel-request-docs/assets/38973929/8ffdbbc1-45c7-4a30-8a7a-cb02f448812a)

![2](https://github.com/rakutentech/laravel-request-docs/assets/38973929/d64a7896-4e1d-49cd-bd01-eb0d42503471)

**Comment by kevincobain2000** [comment]
Hmmm ok. 

Base path is not compatible. Actually it won’t be compatible.
