### ISSUE TITLE
Cannot parse Json String on body request

### ISSUE THREAD

**Issue by KyoRion** [rakutentech/laravel-request-docs#23]
![image](https://user-images.githubusercontent.com/26852023/140688913-93ed2119-4861-4f77-a36e-fbffbbdf1b8e.png)

I got issue when using package have using json input but it's not work please check it out! 
I guess I do something wrong maybe...

**Comment by kevincobain2000** [comment]
That is because of backticks is not a valid JSON.

```
{
	"type": "haha",
         "sub_cate": `{
                     ↑ ` backtick is not a valid json
```
