### ISSUE TITLE
vendor/rakutentech/laravel-request-docs/resources/dist/index.html): Failed to open stream: No such file or directory [BUG] 

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [rakutentech/laravel-request-docs#230]
OS: WINDOWS
Browser: Chrome
Laravel Version: 9/10
PHP Version: 8.1/8.2
Laravel Request Docs Version: 1.31

**Comment by kevincobain2000** [comment]
Seems like you have updated from the previous package?
Please try a fresh install

**Comment by dmitryvasilevskiy** [comment]
yes from 2.16 to 1.31

**Comment by dmitryvasilevskiy** [comment]
project clone again and start work

p/s magic:)
p/s delete vendor dont helped(
