### ISSUE TITLE
Specify response schema

### ISSUE THREAD

**Issue by Azoorb** [rakutentech/laravel-request-docs#231]
Hi, thanks for your package, amazing job

The automatic retrieval of the validation fields to build the body doc of the query is very smart. But I'm very frustrated not to have the same system for the request response.

On the backend, it would be enough to add something like this:
```php
class HelloController extends Controller
{
    /**
     * @lrd:start
     * Hello markdown
     * Free `code` or *text* to write documentation in markdown
     * @lrd:end
     * @LRDresponseSchema App\Responses\MyResponse
     */
    public function index(): JsonResponse
    {
        return MyResponse::json($my_model);
    }
}
```
```php
<?php

namespace App\Responses;


class MyResponse
{
    public int $age;
    public string $name;
    /** @var string[] */
    public array $roles;
}

```

Would it be possible, on the frontend, to have a specific field to display the schema of the response? I think it's possible to do it in the description, but I don't think this is the right place to do it. Something like this: 

![laravel-request-docs-frontend](https://github.com/rakutentech/laravel-request-docs/assets/65257077/a72e8e49-8023-4ceb-b02b-95fa30603e2b)

This is just an idea, but I think good documentation should include the schema of the response, and that without having to write it in a php comment. 

Thanks for your work!

**Comment by kevincobain2000** [comment]
Open to pull reqs
