### ISSUE TITLE
[BUG] Wrong request body generation for the array type

### ISSUE THREAD

**Issue by Brainiac24** [rakutentech/laravel-request-docs#232]
Hi! First of all thank you for the best package for generating docs for Laravel!

There is wrong implementation for the array validation in request body.

**Steps to reproduce the behavior:**
Generate form request file and set this kind of rules:

```
public function rules()
{
  return [
    'event_id' => 'required|integer',
    'config.name' => 'nullable|string',
    'config.label' => 'required|string',
    'config.is_required' => 'required|boolean',
    'config.is_active' => 'required|boolean',
  ];
}
```

**Generated request body**
```
{
  "event_id": 2,
  "config.name": "Devin Gulgowski",
  "config.label": "Roberta Ziemann",
  "config.is_required": false,
  "config.is_active": true
}

```
**Expected behavior**
The correct expected request body generation should be: 

```
{
  "event_id": 2,
  "config": [
    {
      "name": "Devin Gulgowski",
      "label": "Roberta Ziemann",
      "is_required": false,
      "is_active": true
    }
  ]
}
```

**Desktop:**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 112.0.5615.165

**Versions (please complete the following information):**
- Laravel Version: 9
- PHP Version: 8.1
- Laravel Request Docs Version: 1.31

Thanks! Hope it will get fixed soon), because it gets a lot of work for me to fix body requests by hand before testing apis. =)

**Comment by kevincobain2000** [comment]
This is fixable. Thanks for reporting.
About soon I am not sure but will look into pull req.
If you are in a hurry then following is the component that handles the body request

https://github.com/rakutentech/laravel-request-docs/blob/09c7b2b35da7afd760478ebef7ec3c37bc9149ab/ui/src/components/ApiAction.tsx#L247-L267
