### ISSUE TITLE
[BUG] NGINX and vendor publish

### ISSUE THREAD

**Issue by mdoulabi1** [rakutentech/laravel-request-docs#234]
Hi
I use laravel-request in my local withou any problem but when i wanna use it in my server i just  get 1!!
nothing else show
i enabled debug to true to debug this error but nothing show
can you help me?

my laravel-request-docs version :         "rakutentech/laravel-request-docs": "^2.1

my browser console says : Failed to load resource: the server responded with a status of 404 () 
request-docs/_astro/App.daaa028c.js
this file exists in my vendor directory but can't load

**Comment by kevincobain2000** [comment]
How about `config('request-docs.enabled')`?
This should be enabled as well.

Also check `php artisan route:list|grep "request-docs"`

https://github.com/rakutentech/laravel-request-docs/blob/09c7b2b35da7afd760478ebef7ec3c37bc9149ab/src/LaravelRequestDocsServiceProvider.php#L29

**Comment by mdoulabi1** [comment]
> 



> How about `config('request-docs.enabled')`? This should be enabled as well.
> 
> Also check `php artisan route:list|grep "request-docs"`
> 
> https://github.com/rakutentech/laravel-request-docs/blob/09c7b2b35da7afd760478ebef7ec3c37bc9149ab/src/LaravelRequestDocsServiceProvider.php#L29

i chek `config('request-docs.enabled')` and it's true and work as well
but this command `php artisan route:list|grep "request-docs"` show nothing and done

**Comment by mdoulabi1** [comment]
> i check `config('request-docs.enabled')` and it's true and work as well
> but this command `php artisan route:list|grep "request-docs"` show nothing and done

**Comment by kevincobain2000** [comment]
oh ok then I think you upgraded this lib from the previous versions?
If that so, then could you please try a fresh install?
Meaning removing the `public/vendor/<rakutentech-laravel-docs` completely, as in this version 2.0 only config needs to be published, not the assets this time.

**Comment by mdoulabi1** [comment]
> oh ok then I think you upgraded this lib from the previous versions? If that so, then could you please try a fresh install? Meaning removing the `public/vendor/<rakutentech-laravel-docs` completely, as in this version 2.0 only config needs to be published, not the assets this time.

there is no file in` public/vendor/<rakutentech-laravel-docs` directory
how can i publishe the assets?
i directly install the latest version and i did't upgrade

**Comment by kevincobain2000** [comment]
There is no need to publish assets. The assets are picked up automatically. 

One more question. Are you using any base url other than root?


Anyways, the assets that are giving you 404. are here. https://github.com/rakutentech/laravel-request-docs/tree/master/resources/dist/_astro

You could try and manually copy those to your public dir. 
However I am not sure why these are not picked automatically in your project.

**Comment by mdoulabi1** [comment]
> There is no need to publish assets. The assets are picked up automatically.
> 
> One more question. Are you using any base url other than root?
> 
> Anyways, the assets that are giving you 404. are here. https://github.com/rakutentech/laravel-request-docs/tree/master/resources/dist/_astro
> 
> You could try and manually copy those to your public dir. However I am not sure why these are not picked automatically in your project.

no i'm not using .you know there are a lot of assets in my public dir and they're loading correctly

**Comment by kevincobain2000** [comment]
In that case, I have no idea why `.daaa028c.js` is giving you 404.

**Comment by mdoulabi1** [comment]
i think the it has bug in subdomain
can you check it?

**Comment by abodnar** [comment]
I am having a similar issue as well when the docs are deployed to servers and in particular won't load on Safari.

<img width="862" alt="Screenshot 2023-05-24 at 11 57 05 AM" src="https://github.com/rakutentech/laravel-request-docs/assets/1891200/e7d165fa-f028-456a-9b2d-64811542e6a7">

Now what's interesting is if I load the docs up in Chrome and refresh the page a few times, the docs will load and everything works. This does not work in Safari though.

**Comment by abodnar** [comment]
What do you need me to do?

**Comment by kevincobain2000** [comment]
@abodnar find the cause

**Comment by abodnar** [comment]
Ok, so one of the things I'm noticing is that it is not returning all of the App.daaa028c.js file when I go to load it, even when accessing that file directly in my browser or calling it through curl, it seems like the content-length is always 744828

**Comment by kevincobain2000** [comment]
Wow thanks.
That's weird, this is first time I am knowing about this.

Following is the code that gives the assets

https://github.com/rakutentech/laravel-request-docs/blob/09c7b2b35da7afd760478ebef7ec3c37bc9149ab/src/Controllers/LaravelRequestDocsController.php#L89-L120

**Comment by abodnar** [comment]
Yeah, I looked at that. I'm starting to think this could be an Nginx or load balancer type issue. Going to work with my devops team to see if they can tell what's going on.

**Comment by jeramyhing** [comment]
I'm having the same issue as described above. 

I have installed the latest package fresh, not an upgrade, into a Laravel 10 project. 

Everything, works perfectly on my local. However, when deployed to the development server it only shows a "1" on a blank/white page. The deployment pipeline runs composer install and I see the package on the server when I ssh in. In comparison to my local, all the files are there.

I originally made the following changes to the config:

```diff
-    'url' => 'request-docs',
+    'url' => 'docs',
...

-    'only_route_uri_start_with' => '',
+    'only_route_uri_start_with' => 'api',

```
> Note: I have tried reverting these configs to the published defaults on the server and still get the same result.

@mdoulabi1 made a comment about subdomains, which is exactly my situation. My dev server has the subdomain of `dev.api.domain.com`. My server logs show entries as such:

```
2023/05/25 23:31:13 [error] 129747#129747: *1435 open() "/sites/dev.api.domain.com/files/public/request-docs/_astro/index.2d180189.css" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: dev.api.domain.com, request: "GET /request-docs/_astro/index.2d180189.css HTTP/2.0", host: "dev.api.domain.com", referrer: "https://dev.api.domain.com/docs"
2023/05/25 23:31:13 [error] 129747#129747: *1435 open() "/sites/dev.api.domain.com/files/public/request-docs/_astro/App.daaa028c.js" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: dev.api.domain.com, request: "GET /request-docs/_astro/App.daaa028c.js HTTP/2.0", host: "dev.api.domain.com", referrer: "https://dev.api.domain.com/docs"
2023/05/25 23:31:13 [error] 129747#129747: *1435 open() "/sites/dev.api.domain.com/files/public/request-docs/_astro/client.8c8eb78c.js" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: dev.api.domain.com, request: "GET /request-docs/_astro/client.8c8eb78c.js HTTP/2.0", host: "dev.api.domain.com", referrer: "https://dev.api.domain.com/docs"
```

@abodnar mentioned his nginx setup, which is also my setup as well. I hope these commonalities will help you to solve this issue. It seems this problem is a shared, possibly growing problem, and very recent. It took me a while to find this thread because it was simply labeled BUG, plus it's too new for the search engines.

This is a great package, I sure would love to use it in this project. Let me know if I can help you solve this problem in anyway.

**Comment by chamal101** [comment]
I'm having the same issue. Did anyone manage to resolve this?

It can't be a sub-domain issue as I tried a top level domain in prod. However, it's working fine in my local machine.

**Comment by abodnar** [comment]
Nothing from me yet.

Now interestingly, I was checking another application's dev environment that has the package installed and it loaded the documentation. But when I went to its staging server for that application, the package didn't load. So definitely a weird situation.

**Comment by mdoulabi1** [comment]
> I'm having the same issue. Did anyone manage to resolve this?
> 
> It can't be a sub-domain issue as I tried a top level domain in prod. However, it's working fine in my local machine.
the assets that are giving you 404. are here. https://github.com/rakutentech/laravel-request-docs/tree/master/resources/dist/_astro

You could try and manually copy those to your public dir.
you can this solution until this bug fix

**Comment by mdoulabi1** [comment]
> Nothing from me yet.
> 
> Now interestingly, I was checking another application's dev environment that has the package installed and it loaded the documentation. But when I went to its staging server for that application, the package didn't load. So definitely a weird situation.


the assets that are giving you 404. are here. https://github.com/rakutentech/laravel-request-docs/tree/master/resources/dist/_astro

You could try and manually copy those to your public dir.
you can this solution until this bug fix

**Comment by chamal101** [comment]
Thank you @mdoulabi1 . Copying the assets manually to the public folder fixed the issue.

**Comment by kevincobain2000** [comment]
We should create a publish assets command as substitute for those having same issue.

**Comment by jeramyhing** [comment]
> Thank you @mdoulabi1 . Copying the assets manually to the public folder fixed the issue.

Same here, that temporarily fixes the issue for me. Looking forward to having a permanent solution. Thank you.

**Comment by th3third** [comment]
Hey everyone, I was experiencing this issue too, and I found the cause for it. I was receiving a 404 response from my Nginx server specifically - it was not even hitting the access logs. I then noticed it only did this for specific types of files: css, jpeg, mp4, etc. It would hit the access logs and return a Laravel 404 for other file extension types.

Upon looking in the configuration, I saw this block:
` location ~* .(css|mp4jpeg|gif|png)$ {`

Commenting out that block fixed the issue. That's why placing the files in the root works for a lot of people. They're likely using a similar configuration and once the files are moved to the root, they're findable on the server once again using this block because it uses the root to try and grab those files.

On localhost, this configuration probably doesn't exist, which is why it works there.

**Comment by abodnar** [comment]
My nginx conf:

```
server {
    listen 80;
    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

**Comment by kevincobain2000** [comment]
@th3third genius

**Comment by kevincobain2000** [comment]
Thank you all.

It seemed like you needed to copy and paste the assets manually to your public folder.
Please see the pull req below so you can publish the assets to public for some NGINX users.

https://github.com/rakutentech/laravel-request-docs/pull/249
