### ISSUE TITLE
Make it possible to make rules for array in request body.

### ISSUE THREAD

**Issue by ennisthemenace** [rakutentech/laravel-request-docs#237]
I am not sure if this is possible as it when looking at the documentation, but I am trying 
Make rules that allow for request body to be an array? 
[{
  "reseller_uuid": "",
  "coupon_code": ""
},...]

My rules function would look like this
 function rules()
    {
        return [
            //coupons
            '*.reseller_uuid' => 'required|exists:reseller,uuid',
            '*.coupon_code' => 'required|string'
        ];
    }
Sorry to bother if this is already possible I just can't seem to find it in docs.

**Comment by kevincobain2000** [comment]
Not possible right now but can be made possible

**Comment by ennisthemenace** [comment]
Cheers Kevin :)

**Comment by kevincobain2000** [comment]
lol thanks @ennisthemenace 
Although no promise on timeline.

If you want to submit a pull req then this is closely related issue https://github.com/rakutentech/laravel-request-docs/issues/186 and https://github.com/rakutentech/laravel-request-docs/pull/199

**Comment by ennisthemenace** [comment]
It's no biggie for now I just told my frontend dev to assume he can send arrays hehe :)
