### ISSUE TITLE
[BUG]  Not working in production servers

### ISSUE THREAD

**Issue by chamal101** [rakutentech/laravel-request-docs#238]
It's works like a charm for me in my local docker container, but when hosted I get a blank screen that returns 1. 

Asset URLs are throwing 500 errors as well.

Is there something we can do to fix this?

![image](https://github.com/rakutentech/laravel-request-docs/assets/66897146/89339ace-9a41-4960-848b-c2a101eec982)

**Comment by kevincobain2000** [comment]
#234

**Comment by kevincobain2000** [comment]
Duplicate
