### ISSUE TITLE
How to hide all route but show only api route

### ISSUE THREAD

**Issue by teguh02** [rakutentech/laravel-request-docs#24]
Hello my name is teguh, i have one question here. I want to hide all route but show only route with prefix /api/

See image below

![image](https://user-images.githubusercontent.com/43981051/141054032-458a30ad-bc4a-45f0-a232-01d086e3c3da.png)

**Comment by kevincobain2000** [comment]
Yes this is a good idea. I Will work on it.
I am sorry I had been really busy following up on any of your precious posted issues, because of my busy schedule (deadlines).
Will pick up on all the issues within 2021.

**Comment by kevincobain2000** [comment]
I think this can be done via existing config.
https://github.com/rakutentech/laravel-request-docs/blob/master/config/request-docs.php#L28
