### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bry221996** [rakutentech/laravel-request-docs#240]
**Describe the bug**
Showing only POST request, Other request is not showing

**Expected behavior**
All Request should be visible

**Screenshots**

![image](https://github.com/rakutentech/laravel-request-docs/assets/51357035/c164fada-ac44-4246-a86f-65d816e1d9b9)
![image](https://github.com/rakutentech/laravel-request-docs/assets/51357035/584d447a-d434-46d8-ab2e-3a6728ddcc95)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]: Ubuntu
 - Browser [e.g. chrome, safari]: Chrome

**Versions (please complete the following information):**
- Laravel Version: 9
- PHP Version: PHP 8.2.6
- Laravel Request Docs Version: ^2.16

**Comment by bry221996** [comment]
Request Change in `LaravelRequestDocsController.php`


````
        $showGet    = !$request->has('showGet') || filter_var($request->input('showGet'), FILTER_VALIDATE_BOOLEAN);
        $showPost   = !$request->has('showPost') || filter_var($request->input('showPost'), FILTER_VALIDATE_BOOLEAN);
        $showPut    = !$request->has('showPut') || filter_var($request->input('showPut'), FILTER_VALIDATE_BOOLEAN);
        $showPatch  = !$request->has('showPatch') || filter_var($request->input('showPatch'), FILTER_VALIDATE_BOOLEAN);
        $showDelete = !$request->has('showDelete') || filter_var($request->input('showDelete'), FILTER_VALIDATE_BOOLEAN);
        $showHead   = !$request->has('showHead') || filter_var($request->input('showHead'), FILTER_VALIDATE_BOOLEAN);

**Comment by bry221996** [comment]
Any updated on this @kitloong @kevincobain2000

**Comment by kitloong** [comment]
Hi @bry221996 I am sorry for the late reply.

I have done some investigation and tried to reproduce the error however I failed to do so.

Could you please provide minimal steps to reproduce it? A new fresh Laravel would be a good start.
