### ISSUE TITLE
Show custom rule docs instead of class

### ISSUE THREAD

**Issue by beerik94** [rakutentech/laravel-request-docs#244]
Right now if you add a custom validation rule to a request it shows the path to the class in the request docs.
![image](https://github.com/rakutentech/laravel-request-docs/assets/3193332/5ea7adcb-b53c-43c1-a78d-cb9fb2520c92)

I would like to propose to show the phpdoc from the class itself so that I won't have to explain to all my front end devs what a certain rule does (even though I think my class names are self explanatory)

**Comment by kevincobain2000** [comment]
feel free to submit a pull req
