### ISSUE TITLE
Rollback executed database queries while testing request.

### ISSUE THREAD

**Issue by souravdutt** [rakutentech/laravel-request-docs#247]
Hi.. it is a really great and very useful library/package. 

I think there should be an option in this package to **turn on/off rollback all (or a specific if possible) executed queries when testing through the API request docs. (I mean rollback only for requests sent through laravel-request-docs UI).**

Hope you understand why I'm suggesting rolling back all queries, but I want to share my views on, **why allowing/disabling some specific queries**:
**_Suppose I'm trying to test login through which I get auth token which needs to be saved into the database so that I can test other authorized requests._**

I'm not sure if there is already an option, if so please pardon me.

Thanks!

**Comment by kevincobain2000** [comment]
I mean interesting, but that is a complicated thing to solve as many users may use the dashboard on your system.
We can keep a track of what queries were executed by LRD, but if you can suggest a way on how to rollback them.
Some controllers may have their own transaction and commit without revealing the transaction id, so I don't think it is that easy as it may sound.
Overall appealing feature but hard to implement.
