### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by manoj-xelp** [rakutentech/laravel-request-docs#248]
Hey,
Can the api's be divided into different groups via versioning?

Ex: 
Parent V1:
       -Api1
       -Api2
Parent V2:
       -Api1

Currently, it's showing all endpoints in a single list.

And Is it possible to have different docs to each groups?
Ex: Providing a v1 doc to particular vendor access and v2 to other vendors.

**Comment by kevincobain2000** [comment]
Currently it is not possible. It is doable however

**Comment by manoj-xelp** [comment]
Can I expect both features in a future release?
