### ISSUE TITLE
Get body params from request()->validate()

### ISSUE THREAD

**Issue by LucaF87** [rakutentech/laravel-request-docs#258]
Hi,
Is possible to capture the body params without create customRequest ? 
ES: VehicleController.php

public function create(Request $request) {

       $this->authorize('AdminCreate', Vehicle::class);

        $data = $request->validate([
            'name' => 'required|string',
            'note' => 'nullable|string'
        ]);

**Comment by kevincobain2000** [comment]
Sorry. This is not possible.
