### ISSUE TITLE
Support Array output

### ISSUE THREAD

**Issue by fishheadcode** [rakutentech/laravel-request-docs#26]
If you have a parameter like a billing address you cant make an array "billing" containing values like "firstname" and "lastname". Instead you need to need make "billing_firstname" and "billing_lastname"

**Comment by fishheadcode** [comment]
Please take also a look at this: https://laravel.com/docs/5.5/validation#validating-arrays

I now defined the array validation in the rules, everything is working fine when checking, but the frontend is generating "billing.firstname": "testuser" instead of "billing": [{ "firstname": "testuser" }]. 

So said, when its an array validation 
- the display must differ
- the request body must be changed

**Comment by kevincobain2000** [comment]
Fixed
