### ISSUE TITLE
Document Page Custom title

### ISSUE THREAD

**Issue by cdmathukiya** [rakutentech/laravel-request-docs#260]
I want to change title of the page at here
![image](https://github.com/rakutentech/laravel-request-docs/assets/18529326/d55e4254-a167-4945-97a6-d4f5c984acef)

I think i was there before in config option. I don't know why it is removed.
![image](https://github.com/rakutentech/laravel-request-docs/assets/18529326/30f01bf6-0fcf-494a-aa93-afba0312d5f2)

If possibiel please add it.

Thank you
Chintan

**Comment by kevincobain2000** [comment]
Thanks. 
I d be open to pull requests.
