### ISSUE TITLE
[BUG] api.php in another route so i get an error "not valid JSON"

### ISSUE THREAD

**Issue by marcmaalouly** [rakutentech/laravel-request-docs#261]
I'm using Laravel 10 with Laravel modules (by nwidart) package that is responsible to create Modules and apply DDD architecture.
So in my case my api.php is in each module like the following screenshot:
![image](https://github.com/rakutentech/laravel-request-docs/assets/65512028/2fd61675-f3fc-4db3-b08a-9b497dc7206e)
I tried reading the documentation and the request-docs.config but didn't find any place to set the path of the api.php folders

**Comment by kevincobain2000** [comment]
Similar issue here 

https://github.com/rakutentech/laravel-request-docs/issues/214

**Comment by ManuelH6** [comment]
> I'm using Laravel 10 with Laravel modules (by nwidart) package that is responsible to create Modules and apply DDD architecture. So in my case my api.php is in each module like the following screenshot: ![image](https://user-images.githubusercontent.com/65512028/254924678-2fd61675-f3fc-4db3-b08a-9b497dc7206e.png) I tried reading the documentation and the request-docs.config but didn't find any place to set the path of the api.php folders



I don't know what was it for you, but I resolve mine by changing the way I defined the routes:

I had an update route defined like this:

`Route::put('/update-user/{user_id}', 'ApiUserController@update');`

So i changed it into that:

`Route::post('/update-user/{user_id}', [ApiUserController::class, 'update']);`

That's all.

For further information about your error, check your browser console.

**Comment by ManuelH6** [comment]
I don't know what was it for you, but I resolve mine by changing the way I defined the routes:

I had an update route defined like this:

`Route::put('/update-user/{user_id}', 'ApiUserController@update');`

So i changed it into that:

`Route::post('/update-user/{user_id}', [ApiUserController::class, 'update']);`

That's all.

For further information about your error, check your browser console.

**Comment by kevincobain2000** [comment]
Thanks @ManuelH6
