### ISSUE TITLE
My API end-points are not discovered by LARAVEL REQUEST DOCS package

### ISSUE THREAD

**Issue by Nes-cmd** [rakutentech/laravel-request-docs#262]
I have been using this package to generate api-doc for my laravel project. This package is best of all of what I know. But recently My API end-points are not discovered by the package. The command `php artisan lrd:generate` is also not there. After installing the package and caching the route, if i visit localhost:8000/request-docs there is nothing in the api list. Please anyone help!

Thanks.

**Comment by kevincobain2000** [comment]
Hmm. What’s the output of /reques-docs/api?

**Comment by Nes-cmd** [comment]
The output of /request-docs/api? is [ ] (empty array).

**Comment by kevincobain2000** [comment]
it shouldn't be, did you upgrade from 1.x to 2.x?
If that so you might need to republish the config

**Comment by kevincobain2000** [comment]
Were you able to find out?

**Comment by Nes-cmd** [comment]
> Were you able to find out?

Yeah, The problem was in web.php. When I comment out all routes in web.php, the package(this package) starts discovering api routes as specified in config (request-docs.php) file. Then I uncommented routes in web.php one by one this time everything is working. I am not sure what was the problem.
