### ISSUE TITLE
FEATURE - Support for route grouping

### ISSUE THREAD

**Issue by LeMatosDeFuk** [rakutentech/laravel-request-docs#263]
Hello, I appreciate all the hard work you've put into this package. I really love it! However, there's one feature I feel is missing - the ability to group routes. Currently, I have numerous endpoints like:

GET api/v1/users
GET api/v1/users/{user}
POST api/v1/users
...
....
GET api/v1/posts
GET api/v1/posts/{post}
POST api/v1/posts

It would be great if I could organize them under specific titles, such as "USERS" and "POSTS," to make it easier to manage. For instance:

**Users**
GET api/v1/users
GET api/v1/users/{user}
POST api/v1/users

**Posts**
GET api/v1/posts
GET api/v1/posts/{post}
POST api/v1/posts

This way, with a large number of endpoints, it won't be as chaotic to navigate and maintain.

**Comment by simonemarino** [comment]
Hello, this bundle is great, but it is possible to group routes as required by @LeMatosDeFuk. Thank you

**Comment by kevincobain2000** [comment]
it is already supported from the UI

**Comment by simonemarino** [comment]
Yes, don't is possible tag with custom string to group routes.

Posts
GET api/v1/posts
GET api/v1/posts/{post}
POST api/v1/posts

Now it is possible to group only with an api pattern by defining it inside the configuration file "request-docs.php" as below

api/v1/posts
GET api/v1/posts
GET api/v1/posts/{post}
POST api/v1/posts
