### ISSUE TITLE
Change The Open API Export JSON Document Title

### ISSUE THREAD

**Issue by hafijul233** [rakutentech/laravel-request-docs#265]
**Is your feature request related to a problem? Please describe.**
On Version 1.25, I was using could change the title of Document. I would very appreciate for that feature.

**Describe the solution you'd like**
If at least I can add title & description to Export JSON that will be helpful.

**Describe alternatives you've considered**
I thought of using the older version as, our system is using a older PHP & Laravel

**Comment by kevincobain2000** [comment]
The code that needs to be changed is 

https://github.com/rakutentech/laravel-request-docs/blob/5c71ac65a04d8872a1269336740e0455466b2833/src/LaravelRequestDocsToOpenApi.php#L17 

```
 $this->openApi['info']['title']           = config('request-docs.open_api.title', 'Laravel Request Docs');
```

and the add to the config

if you can submit a pull req, I can merge it.

**Comment by kevincobain2000** [comment]
https://github.com/rakutentech/laravel-request-docs/commit/a8f67be057627060ce24aaaac4aa06b597fc734a

**Comment by hafijul233** [comment]
Thank for  this update
