### ISSUE TITLE
[BUG] Latest Version does not support Open API 3.0 PathParameter and Delete request body standard

### ISSUE THREAD

**Issue by hafijul233** [rakutentech/laravel-request-docs#266]
**Describe the bug**
While I tried to use the OPENAPI 3 export from version 2.17 on swagger editor. It throw `Symmetrical` & `Structural` error while parsing the JSON. So The issues I faced
1. *Semantic error at paths./api/v1/meta-data/countries/{country}
`Declared path parameter "country" needs to be defined as a path parameter at either the path or operation level`* 
2. *Semantic error at paths.api/v1/users/{user}.delete.requestBody
`DELETE operations cannot have a requestBody`.*

**To Reproduce**
1. Create an API collection that has `DELETE` HTTP method API
2. Create another API on that collection with having a path parameter
3. Export OPENAPI3 JSON 
4. Upload it info [Swagger Editor](https://editor.swagger.io/)
5. On right side those error will display

**Expected behavior**
Probability support of OPENAPI3 without exceptions

**Screenshots**
![issue](https://github.com/rakutentech/laravel-request-docs/assets/24684511/18d2ad75-0ba8-4fc3-b203-b050aadeec56)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser Chrome
 - Version 115

**Versions (please complete the following information):**
- Laravel Version: 10.17.1
- PHP Version: 8.1.21
- Laravel Request Docs Version: 2.17

**Comment by kevincobain2000** [comment]
No idea

**Comment by hafijul233** [comment]
Okay. I did some debugging, The `Semantic Error`, was caused because the `{city}` keyword in the API URL is defined as a query string but that is actually a path parameter, not a query value. And for the Delete operation, OpenAPI 3 Specs discourage sending request body for the DELETE request.

## I made those two options as configuration, I will send a Pull Request so you can verify.
