### ISSUE TITLE
[BUG] Unable to reach /request-docs/api 

### ISSUE THREAD

**Issue by devsuitup** [rakutentech/laravel-request-docs#275]
**Summary**
/request-docs/api is throwing a 404, even though /request-docs answers fine

**To Reproduce**
1. on an existing project providing an api exposed on /api
2. `composer require rakutentech/laravel-request-docs`
3. `php artisan vendor:publish --tag=request-docs-config`
4. `php artisan vendor:publish --tag=request-docs-assets`
5. `php artisan route:cache`
6. `php artisan config:cache`
7. `php artisan serve`
8. no error is shown

**Expected behavior**
/request-docs/api serving the expected json

**Screenshots**
![image](https://github.com/rakutentech/laravel-request-docs/assets/2380987/334f9b2c-6d2b-4716-a4f7-d04a94955573)

![image](https://github.com/rakutentech/laravel-request-docs/assets/2380987/d321973b-a725-4227-9213-212557df8707)

**Versions (please complete the following information):**
- Laravel Version: 9
- PHP Version: 8.1
- Laravel Request Docs Version: 2.22

Thank you for your help !

**Comment by kevincobain2000** [comment]
You don’t need step 4
And config cache should be done before route cache. 

Probably that’s why.

**Comment by devsuitup** [comment]
Why publishing the assets could cause this ? 🤔 
Also, do you have any idea what it could have done that I would need to fix and how...?

Thank you for your help

**Comment by kevincobain2000** [comment]
Nothing much to go on. Please check previous issues, similar issue had been solved before. 
Thanks

**Comment by shravanjha** [comment]
I am having the same issue and looked through all the past solution but nothing working for me.
