### ISSUE TITLE
Slow search in large applications

### ISSUE THREAD

**Issue by IgorMy** [rakutentech/laravel-request-docs#276]
As I mentioned in the title, when you are working with large applications, of hundred of requests, it takes a few seconds to search. Also, it's so slow in typing too. This is because it's not aborting previous search on type.

Could you please add an option to make local search and have a button tu update the content?

**Comment by kevincobain2000** [comment]
A button can be added so that it doesn’t make an api call upon input. 
open to pull reqs.
