### ISSUE TITLE
Route argument not showing correctly

### ISSUE THREAD

**Issue by cdmathukiya** [rakutentech/laravel-request-docs#278]
**Describe the bug**
Route argument with param are not displaying correctly
![image](https://github.com/rakutentech/laravel-request-docs/assets/18529326/4847180b-acdc-4478-a43e-f467499808f8)

**Comment by kevincobain2000** [comment]
Thanks for reporting, you can check the following implementation if the correct route format is fetched properly.
If yes, then will welcome a pull req.
If not, then nothing can be done.

https://github.com/rakutentech/laravel-request-docs/blob/3449b5eb89c175fe1237a0b75808c3bbcc44d292/src/LaravelRequestDocs.php#L158
