### ISSUE TITLE
Generate Response Schema

### ISSUE THREAD

**Issue by Rizki-SS** [rakutentech/laravel-request-docs#279]
Hi, thanks for your package, it was very helpful in documenting my application.

Maybe this is related to issue #231, but it seems there is still no update about this(or actually already exist?).
I feel I need a response schema so I don't need to make a request first to find out. If I only add it in the comments, sometimes I'm still wrong in determining the response schema (typo or wrong data type).

So I thought it might be easier to do as in issue #231. I also thought of adding some response schema based on the status code.
![image](https://github.com/rakutentech/laravel-request-docs/assets/55300337/25111827-ff83-446f-9954-dc7b338c786f)
![image](https://github.com/rakutentech/laravel-request-docs/assets/55300337/be0adeb3-9984-4bbc-950b-e3e44577b7fc)

at least it helps to know and can be updated based on the given model, but I don't know the best way to display it
![image](https://github.com/rakutentech/laravel-request-docs/assets/55300337/a880c46f-28f0-44e2-b98b-4289485daf25)

I also don't know how to customize the export to openapi and I'm not sure, is the process that I made correct?

**Comment by kevincobain2000** [comment]
Generating response schema automatically is not implemented. 
I am open to pull reqs.

**Comment by r4m-sergeya** [comment]
Hi @kevincobain2000,
you says automatically response schema is not implemented, but can I annotate response schema manually by adding some annotations?

**Comment by kevincobain2000** [comment]
@r4m-sergeya yiu can annotate but it doesn’t display on the UI. 

You can however use @lrd:start and add markdown which are displayed on the ui.
