### ISSUE TITLE
it cannot combine with https://restify.binarcode.com/

### ISSUE THREAD

**Issue by trihai306** [rakutentech/laravel-request-docs#281]
[**Describe the bug**

**To Reproduce**
1. `composer create-project laravel/laravel:^10.0 laravel`
2. `composer require rakutentech/laravel-request-docs`
3. `php artisan serve`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]

**Versions (please complete the following information):**
- Laravel Version:
- PHP Version:
- Laravel Request Docs Version:

**Additional context**
](https://restify.binarcode.com/)

**Comment by kevincobain2000** [comment]
It is not supported then for that. Sorry.
