### ISSUE TITLE
[BUG] Missing Documentation

### ISSUE THREAD

**Issue by MLDMoritz** [rakutentech/laravel-request-docs#282]
Many features seem to be undocumented and hidden. I for example cannot configure Bearer auth headers, due to lack of knowledge.

Is there any doc available that I am not aware of?

**Comment by kevincobain2000** [comment]
I understand the lack of knowledge. 

Quick tip: always search previous issues to gain the knowledge 

https://github.com/rakutentech/laravel-request-docs/issues?q=is%3Aissue+authorization+token+is%3Aclosed

**Comment by MLDMoritz** [comment]
Okay, guess Bearer Auth is not possible then. Thanks.

**Comment by kevincobain2000** [comment]
You can edit the request headers.
