### ISSUE TITLE
[BUG] Sorting by Route Name, but grouping by Default results in error

### ISSUE THREAD

**Issue by abodnar** [rakutentech/laravel-request-docs#283]
**Describe the bug**
If I change the sorting of my routes to be by `Route Name` and the grouping is set to `Default`, the response from `request-docs/api` results in an error.

When you look at the response, it is JSON, but it is being returned where it is an object instead of an array because ids are being put in as the keys for the response.

Example:

```
{
    "62": {
        "uri": "api/v1/access-sites",
        ...
    },
    "63": {
        "uri": "api/v1/access-sites",
        ...
    },
    "66": {
        "uri": "api/v1/access-sites",
        ...
    },
    "64": {
        "uri": "api/v1/access-sites/{siteId}",
        ...
    },
    ...
}
```

**To Reproduce**
1. Go to request docs
2. Click gear icon
3. Set Sort by to `Route Names` and group by to `Default`
4. See invalid response red error bar 

**Expected behavior**
The response is always an array so that the docs render without an error.

**Screenshots**
<img width="319" alt="Screenshot 2023-09-06 at 9 54 26 AM" src="https://github.com/rakutentech/laravel-request-docs/assets/1891200/c21315cb-6f49-45d9-99aa-752479ef79c4">

<img width="377" alt="Screenshot 2023-09-06 at 10 00 06 AM" src="https://github.com/rakutentech/laravel-request-docs/assets/1891200/1d7c414d-0609-40ed-9acd-7f82d6a61029">

**Desktop:**
 - OS: Mac
 - Browser Safari
 - Version 16.6

**Versions:**
- Laravel Version: 10.17.1
- PHP Version: 8.1.11
- Laravel Request Docs Version: 2.19 (I did update to 2.22 and still had issue)

**Comment by kevincobain2000** [comment]
なるほど
Thanks for reporting. Would you mind submitting the fix too. 
I ll look into it, probably not soon.

**Comment by abodnar** [comment]
I'll see what I can find. Any direction you can give for me to start at?

**Comment by kevincobain2000** [comment]
The sort and group methods are

https://github.com/rakutentech/laravel-request-docs/blob/73bff56bdc3dd4679a036828ca363333e424a3b4/src/Controllers/LaravelRequestDocsController.php#L59-L61

Setting up local env,

**Comment by abodnar** [comment]
https://github.com/rakutentech/laravel-request-docs/pull/284

**Comment by kevincobain2000** [comment]
cool! Any issues u see with that? @kitloong

**Comment by kevincobain2000** [comment]
released
