### ISSUE TITLE
Support Spatie Laravel Query Builder

### ISSUE THREAD

**Issue by Cryborg** [rakutentech/laravel-request-docs#285]
**Is your feature request related to a problem? Please describe.**
I massively use Spatie Query Builder, and I thought it would be a great addition to LRD if I could see configured filters, sorts and includes for each route.
Here is the link to Spatie Laravel Query Builder : https://spatie.be/docs/laravel-query-builder/v5/introduction

**Describe the solution you'd like**
This would probably need a new keyword in the docs, such as `LRDquerybuilder Model`, `Model` being the model from which the filters, sorts and includes would be taken.

**Describe alternatives you've considered**
I have a separate doc to show this information.

**Comment by kevincobain2000** [comment]
It sounds appealing to add support for this. Idea is to not ask users to add annotations at all, and pick up rules from that automatically. I am not sure if this can be done.

**Comment by Cryborg** [comment]
> It sounds appealing to add support for this. Idea is to not ask users to add annotations at all, and pick up rules from that automatically. I am not sure if this can be done.

I'll try to spend some time to think of a solution, but indeed, as is, I don't think this can be done without any additional code.

**Comment by Cryborg** [comment]
I came up with something very simple.
First, I overload the AllowedFilter class:
```php
<?php

namespace App\Http;

use Spatie\QueryBuilder\AllowedFilter;

class MyAllowedFilter extends AllowedFilter
{
    public function getFilterClass(): string
    {
        return get_class($this->filterClass);
    }

    public function getFilterName(): string
    {
        return $this->name;
    }
}
```
Then I create a Trait with the following method:
```php
    public static function getFiltersData(): array
    {
        $existingFilters = [
            Filter::class => 'custom',
            FiltersExact::class => 'exact',
            FiltersPartial::class => 'partial',
            FiltersCallback::class => 'callback',
            FiltersEndsWithStrict::class => 'ends_with_strict',
            FiltersBeginsWithStrict::class => 'begins_with_strict',
        ];

        $allowedFilters = self::allowedFilters();
        $filtersArray = [];

        foreach ($allowedFilters as $filter) {
            if ($filter instanceof SmiceAllowedFilter) {
                if (array_get($existingFilters, $filterClass = $filter->getFilterClass())) {
                    $filtersArray[] = [
                        'value' => $filter->getFilterName(),
                        'method' => $existingFilters[$filterClass],
                    ];
                }
            }

            if (is_string($filter)) {
                $filtersArray[] = [
                    'value' => $filter,
                    'method' => 'partial',  // default method
                ];
            }
        }

        return $filtersArray;
    }
```
And finally, I use the new overloaded class to declare my filters:
```php
public static function allowedFilters(): array
    {
        return array_merge(
            [SmiceAllowedFilter::exact('axes.id')],
            [SmiceAllowedFilter::exact('criteria_id')],
            [SmiceAllowedFilter::exact('groups.id')],
            [SmiceAllowedFilter::callback('exclusion_filter', function (Builder $query, $value) {
               ...
            })],

            static::$allowedFilters ?? []
        );
    }
```

To retrieve the data, LRD can simply run `Model::getFiltersData();` to retrieve the data:
```php
[
    [
      "value" => "axes.id",
      "method" => "exact",
    ],
    [
      "value" => "criteria_id",
      "method" => "exact",
    ],
    [
      "value" => "groups.id",
      "method" => "exact",
    ],
    [
      "value" => "exclusion_filter",
      "method" => "callback",
    ],
  ]
```
@kevincobain2000 Do you think that would work in LRD?

**Comment by kevincobain2000** [comment]
Thanks, that would work.
I understand that `"value"` is the request query/body key. What is the `"method"` referring to here? Is it the `rule` that we will display on the UI?

All in all, this can work.

Won't close this issue.

**Comment by Cryborg** [comment]
> Thanks, that would work. I understand that `"value"` is the request query/body key. What is the `"method"` referring to here? Is it the `rule` that we will display on the UI?
Exactely, I should have named if "rule" indeed :)

> All in all, this can work.
That would be so great!!

**Comment by kevincobain2000** [comment]
Open to pull reqs.
