### ISSUE TITLE
Support Response analysis

### ISSUE THREAD

**Issue by guillaume047** [rakutentech/laravel-request-docs#287]
I tryed to use it on one of my projects, and it's actually great, the problem i encountered is that the generated doc doesn't tell what the response contains. The frontend developper i was working with always ask me what data this route is returning.

So it would be an absolute killer if this package can analyse Laravel Response in order to make get request more suitable.

**Comment by kevincobain2000** [comment]
Yea man. Pretty much every one has been asking for this feature. 

I ll finally do something about it before this year ends. I promise.
