### ISSUE TITLE
Status codes are not correct, or how can I add them?

### ISSUE THREAD

**Issue by FrazeColder** [rakutentech/laravel-request-docs#288]
Hey everyone,

first of all, thank you for this wonderful package! It really takes of so much work.

However, the status codes shown are not correct. Are those just the default ones, or how are those generated?

In my controller I have the following response:
```
public function update(UpdateCommentRequest $request, Comment $comment): JsonResponse
    {
        $comment = $request->perform($comment);

        return $this->updatedWithPayload(new CommentResource($comment));
    }
```

The `updatedWithPayload` method is part of my Controller which is extended. This is the code for the method
```
public function updatedWithPayload($data, string $message = "The ressource was successfully updated."): JsonResponse
    {
        return $this->successWithPayload($data, $message, 202);
    }
```

Which means, I send a `202` back as a status code. But the generated docs just show me a `200` code instead. Is this a bug? How can I change that etc?

Also, I have a custom status code `483`. This is being thrown in my `EnsureEmailIsVerified` middleware. So, a `483` can be thrown, when the route is protected by the `verified` middleware. I also cannot find the status code `483` in the docs. How can I add them?

Kind regards

**Comment by kevincobain2000** [comment]
Hi

> Are those just the default ones, or how are those generated?

You should be able to override default responses as 

```
    /**
     * @LRDparam username string|max:32
     * // either space or pipe
     * @LRDparam nickaname string|nullable|max:32
     * // override the default response codes
     * @LRDparam responses 200,422
     */
```

or in the config

https://github.com/rakutentech/laravel-request-docs/blob/4f47d1d15733593a2b84a3fa3f6c1e4376afbb2e/config/request-docs.php#L42

--

> Which means, I send a 202 back as a status code. But the generated docs just show me a 200 code instead. Is this a bug?

hmm, you should be seeing 202

https://github.com/rakutentech/laravel-request-docs/blob/4f47d1d15733593a2b84a3fa3f6c1e4376afbb2e/ui/src/components/ApiAction.tsx#L134

try turning off `app.debug` to false and see if mistakenly the middleware is not overriding the status code.

https://github.com/rakutentech/laravel-request-docs/blob/4f47d1d15733593a2b84a3fa3f6c1e4376afbb2e/src/LaravelRequestDocsMiddleware.php#L34C22-L34C31

**Comment by FrazeColder** [comment]
> hmm, you should be seeing 202

What do you mean by the referenced `ApiAction.tsx` line? How can I make use of it or test it?

> try turning off `app.debug` to false and see if mistakenly the middleware is not overriding the status code.

It is already turned off as it is the default setting. Any other idea why it is not showing me a `202`?

**Comment by FrazeColder** [comment]
It is, but it just shows the default response codes and not the response codes which I have implemented such as `202` or `483`

**Comment by FrazeColder** [comment]
Here is the screenshot of the status codes:

![2023-09-26 13 58 47](https://github.com/rakutentech/laravel-request-docs/assets/18104426/c6cfcea5-7721-4171-99ae-89ab4d384888)

**Comment by kevincobain2000** [comment]
ok got it. Well those are the basic status codes that are taken from the config file hard coded.

https://github.com/rakutentech/laravel-request-docs/blob/4f47d1d15733593a2b84a3fa3f6c1e4376afbb2e/ui/src/libs/constants.tsx#L1-L15

These were added just for the reference to the user.
Your status code 201 not showing is due to that. Currently it is not customization via config, I am not sure if many people would desire that feature. If enough people want it, I ll implement it.

**Comment by FrazeColder** [comment]
But the status code `201` and `202` are both included in the hard coded config file, as you have quoted.

Why aren't they showing up? I think I don't understand you.

**Comment by kevincobain2000** [comment]
ah ok, in that case, also need to add their definitions here too, so they are displayed on the UI.
I think you can submit a pull req and I ll merge and push the new tag

```
 export const responsesText: {[key: string]: string} = { 
     "200": "OK", 
     "201": "Created", 
<------------ append here
     "202": "Accepted", 
     "204": "No Content", 
     "400": "Bad Request", 
     "401": "Unauthorized", 
     "403": "Forbidden", 
     "404": "Not Found", 
     "405": "Method Not Allowed", 
     "422": "Unprocessable Entity", 
     "429": "Too Many Requests", 
     "500": "Internal Server Error", 
     "503": "Service Unavailable", 
 } 
```

**Comment by FrazeColder** [comment]
Sorry, I don't understand you.

I thought the generated API docs will display the correct response code. So, if one route response with `201` and another route with `202`, then it will show the correct status code in the documentation. Isn't that the case and feature of this package?

**Comment by kevincobain2000** [comment]
It by default shows all the response codes that are inside the `config/request-docs.php`. For each route, if you need to override those, it can be done using `* @LRDparam responses 200,201`. However, since, the frontend `responsesText` only has limited definitions declared, so even if you put `201` right now, it is not correctly displayed.

**Comment by FrazeColder** [comment]
So, this package does not support to discover the correct response status codes for now and just displays the default ones?

**Comment by kevincobain2000** [comment]
Yes

**Comment by kevincobain2000** [comment]
I ll close this and I have added it to the todo list for next version features.

**Comment by kevincobain2000** [comment]
v2.31

Partially fixed- still custom status codes are not supported. But added more codes ranges that are supported by standard HTTP. Won't support in near future. Pull Reqs welcome.
