### ISSUE TITLE
Please save latest history of Response(Success & Error) 

### ISSUE THREAD

**Issue by hussain-xpeedstudio** [rakutentech/laravel-request-docs#289]
Please store success and error response as like parameters. Otherwise every time we need to hit the api to get sample response

**Comment by kevincobain2000** [comment]
This is doable.

**Comment by kevincobain2000** [comment]
Added to settings on [v2.31](https://github.com/rakutentech/laravel-request-docs/releases/tag/v2.31)

Previous responses are now saved.

![Screenshot 2024-02-13 at 15 30 43](https://github.com/rakutentech/laravel-request-docs/assets/629055/a2b542ef-58bd-4c6c-a5d9-22dc13b79944)
