### ISSUE TITLE
OpenAPI sorted JSON

### ISSUE THREAD

**Issue by Cryborg** [rakutentech/laravel-request-docs#290]
**Is your feature request related to a problem? Please describe.**
In version 1.x, when we generated the OpenAPI JSON (for Postman in my case), the routes list was sorted alphabetically. Now in latest version it is not anymore, and it became a real hassle to find routes when you have 50+ paths and 600+ routes.

**Describe the solution you'd like**
In the OpenAPI JSON, paths should be sorted according to the preferences set in LRD options menu.

**Describe alternatives you've considered**
Manually sorting paths in Postman

**Comment by kevincobain2000** [comment]
You can pass the query param for `sort` as `?sort=route_names` or  `?sort=method_names`

https://github.com/rakutentech/laravel-request-docs/blob/4f47d1d15733593a2b84a3fa3f6c1e4376afbb2e/src/Controllers/LaravelRequestDocsController.php#L60

https://github.com/rakutentech/laravel-request-docs/blob/4f47d1d15733593a2b84a3fa3f6c1e4376afbb2e/src/LaravelRequestDocs.php#L91-L110

**Comment by kevincobain2000** [comment]
>In the OpenAPI JSON, paths should be sorted according to the preferences set in LRD options menu.

yes, that is currently not implemented. Should have been implemented. For now, try manual please.

**Comment by Cryborg** [comment]
> > In the OpenAPI JSON, paths should be sorted according to the preferences set in LRD options menu.
> 
> yes, that is currently not implemented. Should have been implemented. For now, try manual please.

I should have tried this first, thanks! :)

**Comment by kevincobain2000** [comment]
No worries. Cheers. 
will close this. 
if you want add some sort that fits your need. I am ok to merge such pull req and/or will like the proposal. 

As for the UI, fix, will do something about to someday soon.
