### ISSUE TITLE
set prefix for url request

### ISSUE THREAD

**Issue by mahdidev70** [rakutentech/laravel-request-docs#291]
is there any way to set prefix url for all api?
for example set prefix for locale (language) like this:

![Screenshot from 2023-09-26 15-48-11](https://github.com/rakutentech/laravel-request-docs/assets/91634743/73a3ccef-8d09-4c6f-a672-75d2dee2e604)

**Comment by kevincobain2000** [comment]
Not for all API, not at the moment.
You can however, edit the API endpoint before sending.


![Screenshot 2023-09-26 at 22 55 25](https://github.com/rakutentech/laravel-request-docs/assets/629055/1411b2d5-b854-4649-ab05-87b0588a921a)
