### ISSUE TITLE
Adding double quotes into parameters when using with Eloquent LIKE operator.

### ISSUE THREAD

**Issue by souravdutt** [rakutentech/laravel-request-docs#293]
**Description**
I found that API request adding sent through Request-docs interface is adding double quotes into parameters when using with eloquent LIKE operator. For example if I am sending GET request with parameter `&search=test` and if I use it in eloquent 
`$model->where('column', 'like', "%{$req->search}%")`
I get zero result, and lookinto query output I found that above eloquent is used like:
`WHERE column LIKE '%\"test\"%'`
But when I send the same request through **Postman** it works fine.

**Expected behavior**
the query out must be as given below:
`WHERE column LIKE '%test%'`

**Screenshots**
![image](https://github.com/rakutentech/laravel-request-docs/assets/49240259/30bd9dc1-df58-4353-966d-725b9b48139d)
![image](https://github.com/rakutentech/laravel-request-docs/assets/49240259/842e2f11-87c1-4595-a1a3-5096c2424387)

**Comment by kevincobain2000** [comment]
Interesting, try once with `APP_DEBUG=false` in your config. Seems like the middleware that records sql is buggy.
If that doesn't work, then probably on the frontend, it is adding sanitization.

**Comment by souravdutt** [comment]
My bad... I was passing the values incorrectly..
The correct way to pass is `&search=test` (i.e. without quotes) not `&search="test"` 
I can't believe I didn't realize that earlier!

Thanks for your response @kevincobain2000 
And once again, I'm sorry for the oversight.

**Comment by kevincobain2000** [comment]
No worries.
