### ISSUE TITLE
group GEAT and HEAD routes

### ISSUE THREAD

**Issue by ramonpego** [rakutentech/laravel-request-docs#299]
Or you can just filter by default not to display these HEAD routes. Because in the final product, all GET routes are also showing as HEAD

**Comment by kevincobain2000** [comment]
You can use settings and save preferences by toggling

![Screenshot 2023-10-06 at 9 39 37](https://github.com/rakutentech/laravel-request-docs/assets/629055/494e7669-07dd-4e8d-b5f7-128e80067ebc)

--
Right now, via config, this option was removed. If you want to add such a filter, it is fine with me, I can merge it.

Starting points

Add `allowed_methods` array in the config https://github.com/rakutentech/laravel-request-docs/blob/master/config/request-docs.php

Update the implementation here:
https://github.com/rakutentech/laravel-request-docs/blob/33076795d3b4424060c12d3088c689429a487501/src/Controllers/LaravelRequestDocsController.php#L38
