### ISSUE TITLE
PUT routes are being duplicated while others not.

### ISSUE THREAD

**Issue by marensas** [rakutentech/laravel-request-docs#30]
My `api.php` code looks like:

![image](https://user-images.githubusercontent.com/18376464/151351803-1663519e-c691-4200-9fa6-3e417f0e558c.png)

GET, POST, DELETE routes looks nicely grouped:

![image](https://user-images.githubusercontent.com/18376464/151351889-8104992b-babc-4073-aa92-ec17a6e2a23b.png)

But PUT routes are separated to duplicated records for some reason:

![image](https://user-images.githubusercontent.com/18376464/151352071-d4489a19-dabe-4821-b51f-77303c4be2e9.png)

Any ideas why?

Using 1.6 package version.

**Comment by marensas** [comment]
Got it. Laravel `apiResource()` generates `PUT|PATCH` routes together. Same as `GET|HEAD`.

![put-patch](https://user-images.githubusercontent.com/18376464/151371309-a1f0c777-d9a7-4785-8048-f49eb520d2e0.png)
 
But there is a difference between `GET|HEAD`, because these cannot be declared separately - `Route::get()` always generates `GET|HEAD` routes, while `Route::put()` and `Route::patch()` can be declared separately.

Also `apiResource()` have abstract names, like `update`, so 'patch' or 'put' cannot be excluded separetely:

![api resource](https://user-images.githubusercontent.com/18376464/151372850-d1a5d688-12ce-48e2-8061-9523377c63e9.png)

Package code does have `PATCH` routes included, but `HEAD` not. I guess the best solution would be to include both routes with an option in a config, where you can choose to see them or not.

**Comment by kevincobain2000** [comment]
Thanks for reporting. Laravel 9 route list is going to bring some changes. Let me work on this issue together with compatibility with l9.

**Comment by kevincobain2000** [comment]
Should be fixed now
https://github.com/rakutentech/laravel-request-docs/commit/82ba57db053e076f91cceaa166babc7593728d48

**Comment by kevincobain2000** [comment]
Please reopen it if it doesn't work for you.
