### ISSUE TITLE
Markdown comments rendering not working

### ISSUE THREAD

**Issue by MSR2012** [rakutentech/laravel-request-docs#300]
Hi,

I wrote a method like this but can't get those comments rendered on doc page.

    /**
     * @lrd:start
     * Hello markdown
     * Free `code` or *text* to write documentation in markdown
     * @lrd:end
     */
     public function index(Request $request)
     {

     }

Any idea what's wrong here?

**Comment by kevincobain2000** [comment]
can you please proper code tags?
It seems like the tag is used incorrectly because you have posted everything in single line

```
    /**
     * @lrd:start
     * Hello markdown
     * Free `code` or *text* to write documentation in markdown
     * @lrd:end
     */
```

**Comment by MSR2012** [comment]
@kevincobain2000 Edited.

**Comment by kevincobain2000** [comment]
Thanks, will have a look, it shouldn't be.

**Comment by MSR2012** [comment]
@kevincobain2000 I believe I am missing something. Just not sure which thing I did wrong. Although doc page is rendering with all routes url.

**Comment by kevincobain2000** [comment]
Are the markdown comments included properly on the `request-docs/api`?
Just the rendering issue?

**Comment by MSR2012** [comment]
@kevincobain2000 What do you mean by included properly on the request-docs/api? I can see the rendered page but missing markdown commented texts.

**Comment by kevincobain2000** [comment]
I mean. Open domain/request-docs/api
And see if the response contains your markdown

**Comment by MSR2012** [comment]
@kevincobain2000 I don't see any markdown text there but api url is there

**Comment by kevincobain2000** [comment]
Thanks. Not sure, may be your line breaks on the code editor are clashing with CRLF

Implementation looks fine to me https://github.com/rakutentech/laravel-request-docs/blob/master/src/LaravelRequestDocs.php#L293

**Comment by MSR2012** [comment]
@kevincobain2000 Do we need any command to regenerate page/json? Or it does automatically?

**Comment by MSR2012** [comment]
@kevincobain2000 Found the issue, thanks.

**Comment by kevincobain2000** [comment]
It does it automatically.

And what was the issue?

**Comment by MSR2012** [comment]
Issue was in route file, interestingly previous developer use anonymous function to make call. That's why reflection was not working.

`Route::post('logout', fn(Request $request) => (new LoginController())->logout($request));`

**Comment by MSR2012** [comment]
I am closing it as it was a different issue and working.
