### ISSUE TITLE
[BUG] Published assets can not be customized

### ISSUE THREAD

**Issue by cdmathukiya** [rakutentech/laravel-request-docs#304]
**Describe the bug**
I am tring to customize some design changes and want some other customization but It is not affected in generated docs.

**To Reproduce**
<img width="1012" alt="image" src="https://github.com/rakutentech/laravel-request-docs/assets/18529326/d502f2c7-6f23-4c6d-8d25-31daa31d55ab">

<img width="660" alt="image" src="https://github.com/rakutentech/laravel-request-docs/assets/18529326/3fa3db6a-106a-4dbd-abd2-5fdfbaa23f2e">

**Expected behavior**
I want to hide some routes based on user access. Is there any possibilities to pass parameter and access during route list generation time?
I want to pass Id in route param and it is working but it can not access in your `request-docs/api ` route 
<img width="1136" alt="image" src="https://github.com/rakutentech/laravel-request-docs/assets/18529326/87e1d9ae-7c21-45ff-9958-55ff20e6f34b">
I want to create documentation based on user access.

@kevincobain2000  Let me know if is there any possibilities to do this.

Thank you

**Comment by kevincobain2000** [comment]
Yes. Published assets are building a static site using Astro and react. 
Currently these are not customizable via params. To achieve customization, will need to implement via node env variables. 
Mostly you don’t need to publish as the assets are served from Laravel.
