### ISSUE TITLE
Improve readability: Change CSS overflow to 'auto' and remove text truncation for deep PHP arrays

### ISSUE THREAD

**Issue by Plong-Wasin** [rakutentech/laravel-request-docs#306]
**Is your feature request related to a problem? Please describe.**
When using deep PHP arrays, the current CSS setting (`overflow: hidden`) causes the displayed keys to be truncated, making it difficult to read.

**Describe the solution you'd like**
Change the CSS `overflow` property from `hidden` to `auto`  and remove `text-overflow` to allow for horizontal scrolling, enabling users to view the complete keys in deep PHP arrays.

**Additional context**
![image](https://github.com/rakutentech/laravel-request-docs/assets/72617740/e610777e-dc03-440b-aa86-7c7f52d253c1)
Change to
![image](https://github.com/rakutentech/laravel-request-docs/assets/72617740/8cfca693-9e5d-417c-a434-c9701942192c)

**Comment by kevincobain2000** [comment]
Pushed to v2.27
