### ISSUE TITLE
Underscores get replaced to spaces, Am I missing somethings ??

### ISSUE THREAD

**Issue by Jason6809** [rakutentech/laravel-request-docs#309]
**Describe the bug**
As the title, inside the request body underscore get replaced to space.

**To Reproduce**
1. I followed the tutorial, and it just happen unexpectedly.

**Expected behavior**
The underscores should be stay as it is and not replaced to spaces.

**Screenshots**
![Screenshot from 2023-12-08 17-51-28](https://github.com/rakutentech/laravel-request-docs/assets/40509831/ece378a2-6224-4730-b8c7-5f6043679ffc)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 120.0.6099.71 (Official Build) (64-bit)

**Versions (please complete the following information):**
- Laravel Version: v10.35
- PHP Version: 8.1.26
- Laravel Request Docs Version: v2.27

**Additional context**
I'm sorry if there is grammar mistakes, I'm not a English speaker.

**Comment by kevincobain2000** [comment]
Hmmm. I don't think we manipulate that. It shouldn't be.
