### ISSUE TITLE
Undefined variable $docs

### ISSUE THREAD

**Issue by daprezjer** [rakutentech/laravel-request-docs#310]
Just upgraded to the latest after also updating my Laravel to 10. Samples of the new items looks great folks.

However, now that I've upgraded, I simply get:

> Undefined variable $docs

And the generic laravel error page. I can see $docs deep within the package, but I'm not sure where to go from here.  I've:

- deleted and regenerated my request-docs.php
- rerun composer
- adding the optional values to Kernel
- updated composer with the latest and cached the routes, as instructed

Any thoughts on where I should check next?

**Comment by kevincobain2000** [comment]
Look for previous issues. 

A fresh install may help for cases when people have upgraded from v1 to v2
Also you can try with the debug option ON, and find out the error, which will be helpful to locate the issue.
