### ISSUE TITLE
routes's markdowns information

### ISSUE THREAD

**Issue by Caio-mizuno** [rakutentech/laravel-request-docs#312]
I'll appreciate if this project could be more documentated in routes's markdowns information. With a complete documentation what I can describe to show off.

**Comment by Caio-mizuno** [comment]
I was trying to say that there could be better or more detailed documentation on ways to use markdown to describe the functionality of routes. Because there are structures that don't work. And this could shorten the journey when first contacting the lib.

Sorry if I could not express my idea.

**Comment by kevincobain2000** [comment]
Ah ok. Got it. 
Yea, we could expand more on the README.
