### ISSUE TITLE
For a resource controller, every PUT request has resource id also in request

### ISSUE THREAD

**Issue by moh-imran** [rakutentech/laravel-request-docs#313]
For a resource controller, every PUT request has resource id also in request body / request parameters even though it was not provided in UpdateRequest. I have attached the image. How can I fix it?? Thanks in advance.
![doc_image](https://github.com/rakutentech/laravel-request-docs/assets/8580808/20a7c5cd-f502-4389-9cbf-3bc9df752993)

**Comment by kevincobain2000** [comment]
Need more info. Sorry I can't understand your issue well.

**Comment by moh-imran** [comment]
If we have a resource controller (Route::resource('articles')) for rest apis. The update api endpoint should look like:
PUT /articles/{articleId}
Request Params should have **query parameter** but it should not be repeated with **Request** Object. If you see image I attached in first post you will see that **query param** is being repeated in **Request** object also while it was not defined in updateArticleRequest. I hope now its clear.

**Comment by kevincobain2000** [comment]
> Request Params should have query parameter but it should not be repeated with Request Object.

It shouldn't. However, if you ever manually edited the request body, it is saved into localstorage for next use.

The problem doesn't exist on our demo

https://rakutentech.github.io/laravel-request-docs/?api=https://raw.githubusercontent.com/rakutentech/laravel-request-docs/master/ui/public/sample.json#PUTapi/products/{product}

![image](https://github.com/rakutentech/laravel-request-docs/assets/629055/ad364aab-3274-46fc-9105-55d94876c135)
