### ISSUE TITLE
Example Request and Example Response

### ISSUE THREAD

**Issue by DesimirDimitrov** [rakutentech/laravel-request-docs#319]
Is there an easy way to add example requests and example responses?
What about multiple variation requests and responses?

**Comment by kevincobain2000** [comment]
Similar:
https://github.com/rakutentech/laravel-request-docs/issues/287
https://github.com/rakutentech/laravel-request-docs/issues/279
https://github.com/rakutentech/laravel-request-docs/issues/231
https://github.com/rakutentech/laravel-request-docs/issues/208

This is open to pull reqs
