### ISSUE TITLE
Headers docs

### ISSUE THREAD

**Issue by dade1987** [rakutentech/laravel-request-docs#321]
**Is your feature request related to a problem? Please describe.**
How can i documentate my additionals headers?

**Describe the solution you'd like**
Is there a way to put custom headers in the request schema docs?

**Describe alternatives you've considered**
I thought there was a method like LRDheaders X-Token required|string|size:32

**Comment by kevincobain2000** [comment]
Responded here https://github.com/rakutentech/laravel-request-docs/issues/322#issuecomment-1884284662

**Comment by kevincobain2000** [comment]
Fixed in [v2.31](https://github.com/rakutentech/laravel-request-docs/releases/tag/v2.31)
