### ISSUE TITLE
Set Authorization Token

### ISSUE THREAD

**Issue by CodeAddictx10** [rakutentech/laravel-request-docs#323]
It would be great if one could set an authorization token from the UI so one doesn't have to set the Authorization token on every request that needs a token.

**Comment by kevincobain2000** [comment]
It already does that right now. Global headers are need to be saved only once.
![Screenshot 2024-01-20 at 18 32 49](https://github.com/rakutentech/laravel-request-docs/assets/629055/86e0fab8-40d7-438d-867a-64e7b2e5e622)
