### ISSUE TITLE
Adding auth middleware to protect url of request-docs

### ISSUE THREAD

**Issue by Master-r-dev** [rakutentech/laravel-request-docs#324]
In request-docs.php I am trying to add auth middleware , 
but Auth::check() returns false - how can I protect this route that only authorized can see it ?

request-docs.php
===
```
<?php

return [
    'enabled' => true,
    'debug' => true,
    'url' => 'admin/api-docs',
    'middlewares' => [
        'auth:sanctum',
        //Rakutentech\LaravelRequestDocs\NotFoundWhenProduction::class,
    ],
    ...

```
    
    response
===
```
{
  "message": "Unauthenticated."
}
```

**Comment by Master-r-dev** [comment]
if I add routes by coping them from LaravelRequestDocsServiceProvider packageBooted in routes/web (all three including api)   then auth::check() returns correct value but this seems like clumsy solution

**Comment by kevincobain2000** [comment]
hmm adding the middlewares just to the config should have worked.
You sure there isn't a `config:cache` issue or a dangling cookie issue?

**Comment by Master-r-dev** [comment]
Yeah, I tried that too - doesnt work without adding to web.php

**Comment by kevincobain2000** [comment]
hmm, everything works fine on my end. Probably take support from your friends or colleagues to have a second look at your project.
