### ISSUE TITLE
request-docs subdirectory

### ISSUE THREAD

**Issue by gintechsystems** [rakutentech/laravel-request-docs#325]
**Is your feature request related to a problem? Please describe.**
We are temporarily running our project under a v2 subdirectory on our domain. When using v2/request-docs, the page fails to load assets (returning a 404 on all of them).

Its possible this can be done and I am missing something but I did not see an easy configuration option to do this?

**Describe the solution you'd like**
Be able to server request-docs under a subdirectory (public/v2/request-docs)

**Additional context**
<img width="2765" alt="Screenshot 2024-01-24 at 9 46 58 AM" src="https://github.com/rakutentech/laravel-request-docs/assets/10021307/ec2924d6-1b72-4c67-803b-54f098a1e803">

**Comment by kevincobain2000** [comment]
Yea. Base url is not supported. 

Solution here may help https://github.com/rakutentech/laravel-request-docs/issues/234

**Comment by gintechsystems** [comment]
Unfortunately that isn't the best solution for my case. Would be great to see support for this in the future.

**Comment by kevincobain2000** [comment]
Thanks and I feel the pain. The problem is that it can’t be fixed because tin order to support base url, user himself will need to build the frontend by providing baseurl to the fw. The default bundled assets only comes with /
