### ISSUE TITLE
Feature: add support for spatie query builder

### ISSUE THREAD

**Issue by fatm-dev** [rakutentech/laravel-request-docs#326]
Would love to see support for Spatie Query Builder filters and sorts.

**Comment by kevincobain2000** [comment]
Thanks, although I am afraid that is not possible to implement.

**Comment by fatm-dev** [comment]
> Thanks, although I am afraid that is not possible to implement.

Got it. I'll try to make a research as well. Thanks for the reply and thanks for the package )
