### ISSUE TITLE
[BUG] Response error: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by nick322** [rakutentech/laravel-request-docs#327]
**Describe the bug**
About LARAVEL REQUEST DOCS API response failure

**To Reproduce**
1. `composer create-project laravel/laravel:^8.0 laravel`
2. `composer require rakutentech/laravel-request-docs`
3. `app/Http/Kernel.php` add

   ```php
    'api' => [
            ...
            \Rakutentech\LaravelRequestDocs\LaravelRequestDocsMiddleware::class,
   ```

4. `app/Providers/EventServiceProvider.php` add

    ```php
    use Illuminate\Foundation\Http\Events\RequestHandled;
    use Illuminate\Http\JsonResponse;
    use Illuminate\Support\Facades\Event;
    use Illuminate\Support\Facades\Log;

    ...
    public function boot()
    {
        Event::listen(RequestHandled::class, function (RequestHandled $event) {
            $response = $event->response;
            if ($response instanceof JsonResponse) {
                /** @var $response JsonResponse */
                $data = $response->getData() ?: new \StdClass();
            } else {
                $content = $response->getContent();
                $data = json_decode($content) ?: false;
            }

            if ($data === false || !is_object($data)) {
                return;
            }

            $req_hash = $data->req_hash = Str::uuid();
            Log::info('req_hash: ' .$req_hash , $event->request->all());
            
            if ($response instanceof JsonResponse) {
                /** @var $response JsonResponse */
                return $response->setData($data);
            }
            return $response->setContent($data);

        });
    }
    ```

5. `routes/api.php` add

    ```php
    Route::get('/my', function(){
        return response()->json(['data'=> ['a']]);
    });
    ```

6. http://laravel.test/request-docs#GETapi/my 

7. An error occurred while executing send.

**Expected behavior**
There should be information to respond.

**Screenshots**
![截圖 2024-02-02 下午12 20 45](https://github.com/rakutentech/laravel-request-docs/assets/9151347/6011a814-e3d6-4a10-aba0-5a326a342298)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 121.0.6167.85 (x86_64)

**Versions (please complete the following information):**
- Laravel Version: v8.83.27
- Laravel Valet: 4.5.0
- PHP Version: 7.4.33
- Laravel Request Docs Version: v2.28

**Comment by kevincobain2000** [comment]
v2.29

**Comment by nick322** [comment]
@kevincobain2000  Thanks !
