### ISSUE TITLE
Feature Request: Support for Defining Tags in Documentation for SDK Generation with openapi-generator.tech

### ISSUE THREAD

**Issue by robertspektor** [rakutentech/laravel-request-docs#331]
Hello,

I would like to request a new feature that would greatly enhance the usability and functionality of the laravel-request-docs package for developers who rely on openapi-generator.tech for SDK generation.

**Feature Description**
The ability to define custom tags in the documentation generated by laravel-request-docs. These tags are crucial for organizing endpoints into groups/categories in the generated OpenAPI specification, which in turn facilitates the automated generation of client SDKs through tools like openapi-generator.tech. The current version of laravel-request-docs does not seem to support this functionality directly, leading to a manual editing process of the OpenAPI specification post-generation.

**Use Case**
In our use case, we have a Laravel application with a sizable number of routes/endpoints. We are utilizing openapi-generator.tech to automatically generate client SDKs for different platforms. The lack of tag definitions in our OpenAPI specification makes it difficult to categorize these endpoints logically in the generated SDKs.

Proposed Solution
Implement a feature within laravel-request-docs that allows developers to annotate their routes or controllers with custom tags. These tags would then be reflected in the generated OpenAPI specification.

Thank you for considering this request. I look forward to your feedback and am happy to contribute to the discussion or implementation if needed.

Best regards,
Robert

**Comment by kevincobain2000** [comment]
This can be looked into.

**Comment by kevincobain2000** [comment]
Issue moved to requested features.
