### ISSUE TITLE
Implement resources

### ISSUE THREAD

**Issue by palacjon** [rakutentech/laravel-request-docs#338]
Hi there! first at all, thanks alot for this awesome repo.

I think that find in resources to have a preview of json response is a great idea.

Maybe...

**Comment by kevincobain2000** [comment]
Currently looking into it as a matter of fact.

**Comment by Azoorb** [comment]
Maybe we can take inspiration from this package? It perfectly manages to retrieve the schema of the Resources...
https://github.com/dedoc/scramble.git
