### ISSUE TITLE
[BUG] invalid headers generated in curl 

### ISSUE THREAD

**Issue by gabriel-vasile** [rakutentech/laravel-request-docs#343]
**To Reproduce**
1. navigate to https://rakutentech.github.io/laravel-request-docs/?api=https://raw.githubusercontent.com/rakutentech/laravel-request-docs/master/ui/public/sample.json#POSTapi/register
2. click on any request
3. click on *Show curl command*

**Expected behavior**
valid HTTP headers
```
 -H "Content-Type: application/json"
```

**Actual behaviour**
```
 -H "0: Content-Type: application/json"
```

**Comment by kevincobain2000** [comment]
Thanks 
This is first time someone reported this. Which also means that no one ever used the curl feature. 

This should be easy fix.

**Comment by kevincobain2000** [comment]
I couldn't reproduce this. I think it is an issue on the static demo site. The real project doesn't show up index keys.
