### ISSUE TITLE
generated curl command is not friendly for copy-paste

### ISSUE THREAD

**Issue by gabriel-vasile** [rakutentech/laravel-request-docs#344]
I want to be able to copy-paste the generated curl command from LRD to terminal. 

Current situation:
```
curl        <- problem here: new line means command is submitted incomplete
 -X POST
 http://localhost:4321/api/logout
```
To be:
```
curl \
-X POST \
http://localhost:4321/api/logout
```

I'm not sure how to make this compatible with all OSes. `\\\n` is only for unixes, it will not work on windows....

**Comment by kevincobain2000** [comment]
Easy fix. Will fix soon. Probably by weekend.
