### ISSUE TITLE
Security Scheme Missing From Open-API Export

### ISSUE THREAD

**Issue by hafijul233** [rakutentech/laravel-request-docs#349]
**Is your feature request related to a problem? Please describe.**
The problem I am facing is that while exporting OpenAPI collection, it doesn't have a section to define what type of global or endpoint-specific security scheme it has.

**Describe the solution you'd like**
A configuration where users can tel like "bearer", "jwt" or "basic" etc then the tool will add a related section to the collection. Later tools like Postman or Insomnia can display the required option.

**Describe alternatives you've considered**
Every time I explored the file I manually added that section or going Postman to set the authentication type.

**Additional context**
If may be in the future this setting can used on API testing UI as well.

**Comment by hafijul233** [comment]
If anyone is available, I tired to resolve this issue, can review my PR #348

**Comment by kevincobain2000** [comment]
Thanks. Will merge it today
