### ISSUE TITLE
JSON.parse: error when using avaribale or a consts in request validation rules

### ISSUE THREAD

**Issue by mutasemhajhasan** [rakutentech/laravel-request-docs#351]
**Describe the bug**
When writing validation rules if a const used inside the rule it will give this error when accessing the docs
"JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**To Reproduce**
1. Create validation rules
2. Define a const
3. Use a  const inside the rules instead of fixed values, for example if you have a max:5 inside you rule just replace "5" with a variable.
4. php artisan route:cache
5. php artisan serve
6. try accessing the docs and you will get the error

**Expected behavior**
You should be able to use vars or consts inside the rules without any problem

**Screenshots**
![Capture](https://github.com/rakutentech/laravel-request-docs/assets/16334884/f6473daf-d8db-4210-a461-319f89398d1b)

**Versions (please complete the following information):**
- Laravel Version:11.0
- PHP Version:8.2.12
- Laravel Request Docs Version:2.34

**Additional info**
```
class MyApp
{
    const MAX_PROFILE_IMAGE_SIZE = 1024;
}
```
`//..`
`'image' => 'nullable|image|mimes:jpeg,png,jpg|max:'.MyApp::MAX_PROFILE_IMAGE_SIZE ,`
`//...`

**Comment by kevincobain2000** [comment]
Is the const defined in the same class where the rules are?
It’s because the reflection class fails to find that const

**Comment by mutasemhajhasan** [comment]
> Is the const defined in the same class where the rules are? It’s because the reflection class fails to find that const

You are right, the const is not in the same class, when I put it in the same class it works.
