### ISSUE TITLE
Request query parameters are not handled for GET requests

### ISSUE THREAD

**Issue by avinmaster** [rakutentech/laravel-request-docs#352]
**Describe the bug**
I have `index` method (GET route) with custom validation (custom `Request` class). It's reading rules.

**To Reproduce**
Add route to api.php:
```php
Route::get('/digital-books', [DigitalBookController::class, 'index'])
            ->name('digital-books.index');
```
Then in controller:
```php
public function index(DigitalBookIndexRequest $request): DigitalBookCollection
{
       $validated = $request->validated();
       // ...
       return new DigitalBookCollection($books);
}
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 124.0.2

**Versions (please complete the following information):**
- Laravel Version: 10.48.4
- PHP Version: 8.2
- Laravel Request Docs Version: 2.35

**Comment by avinmaster** [comment]
It can't handle rules on index route.

**Comment by kevincobain2000** [comment]
It should. Try with `debug=true` in the config and see if you have any errors in your request file. Usually the rules aren't generated when there are issues in the request file.
