### ISSUE TITLE
Layout adjustment - PHPdocs and Tags

### ISSUE THREAD

**Issue by fernando-piovezan-instar** [rakutentech/laravel-request-docs#362]
Hi @kevincobain2000, 
I am making a layout change to meet a need in my project and I would like to know your opinion on submitting this PR for the project or do you think it is not necessary.
My main problem was not having the option to display description and example for the fields of both BODY PARAMETERS and QUERY PARAMETERS.
After displaying these values, the layout became very confusing so I made an adjustment that ended up changing the screen the way it was. The rules are no longer displayed each on a line, but rather all on a single line, and below we have a collapse to display the descriptions and examples. Below is a print of how it turned out. 
Note. I didn't really like the idea of collapse, but it was what I could think of to display the description and example and not clutter the screen, if you have any suggestions I would be very grateful.

![before](https://github.com/rakutentech/laravel-request-docs/assets/167241768/2fc7490f-01b0-41bb-8bb0-db03fc4e5de0)

![after](https://github.com/rakutentech/laravel-request-docs/assets/167241768/d9e6265c-5cea-4f24-924c-fd754bccb6b9)

Any suggestion is welcome.

Thank's for your time

**Comment by kevincobain2000** [comment]
Let me understand this correctly, where does the description come from? I don't think LRD has a way to parse the description per rule.

**Comment by kevincobain2000** [comment]
This feature has been requested in the past as well, but no one submitted a PR.
I have welcomed such in the past to obtain extra information from `phpdocs` and `@package` tags etc. 
Will look into a PR if submitted. 
Thanks
