### ISSUE TITLE
[BUG] Search results not updating correctly when input text is not cleared

### ISSUE THREAD

**Issue by Plong-Wasin** [rakutentech/laravel-request-docs#370]
**Describe the bug**
When performing a search, if you enter a new search term without clearing the previous text from the search box, the search results do not update correctly. The results displayed are for the previous search term, not the new one.

**To Reproduce**
1. Create route products
2. Go to the search bar.
3. Enter the search term "not found" and press Enter.
4. Observe that results for "not found" are displayed.
5. Without clearing the previous text, enter a new search term, "products".
6. Observe that the search results are not updated and still show results for "not found".

**Expected behavior**
When a new search term is entered in the search box without clearing the previous text, the search results should update to reflect the new search term. In this case, the search results should display results for "products".

**Screenshots**
![image](https://github.com/rakutentech/laravel-request-docs/assets/72617740/dd6a5cee-ab58-45f7-b1a2-791319d4df35)
![image](https://github.com/rakutentech/laravel-request-docs/assets/72617740/ecada872-4eb0-4487-9ad2-4c81abbe1482)
![image](https://github.com/rakutentech/laravel-request-docs/assets/72617740/33c1b725-972b-4d0e-8250-d6d6efa06870)

**Comment by Plong-Wasin** [comment]
This line
https://github.com/rakutentech/laravel-request-docs/blob/cb6264beb7dfb85b53b5dcf403a7f52215a562c6/ui/src/components/App.tsx#L119-L134

I think this change will fix the bug, but it might affect performance.
```diff
-         const fuse = new Fuse(lrdDocsJson, searchOptions);
+        const fuse = new Fuse(lrdDocsJsonCopy, searchOptions);
```


But if we can compare the two texts (text before the change and text after the change) with `afterChange.includes(beforeChange) ? lrdDocsJson : lrdDocsJsonCopy`, I think it can fix the bug and maintain great performance.
```js
const fuse = afterChange.includes(beforeChange) ? new Fuse(lrdDocsJson, searchOptions) : new Fuse(lrdDocsJsonCopy, searchOptions);
```

**Comment by kevincobain2000** [comment]
Thanks. Can you submit the PR for that. I'll merge that

**Comment by kevincobain2000** [comment]
v2.37
