### ISSUE TITLE
Feature Request: sorting and smart filtering features

### ISSUE THREAD

**Issue by avinmaster** [rakutentech/laravel-request-docs#378]
Hi @kevincobain2000 and contributors!
Can we add a sorting and filtering features for API list on sidebar? Everything like in `php artisan route:list` and additional sorting types:
1. Alphabetical;
2. Route parental;
3. From end, parental;
4. Sort as placed in routing PHP files.

What we have in route:list:
1. Filtering by method, name, domain and path (or exception);
2. Reverse sorting;
3. Except/only vendor.

**Comment by kevincobain2000** [comment]
I guess that can be done.
