### ISSUE TITLE
Response type

### ISSUE THREAD

**Issue by rawahamid** [rakutentech/laravel-request-docs#382]
Hello guys

I have faced some problems when using request docs, in some places or while developing a project I want to see some variable values, so I want to use `dd()` function but in the doc’s response it shows HTML so I have either to Log the variable to see or use Postman so I suggest adding some response types like that postman have such JSON, Preview or RAW.

**Comment by kevincobain2000** [comment]
That could be added. Will welcome a PR

**Comment by rawahamid** [comment]
Sorry but didn't use astro before i just suggested if someone could help and do it also another suggestion for do it we can use iframe to show the response type otherwise if someone do it with another it will be good

**Comment by kevincobain2000** [comment]
It’s a react app, Astro is just the packager.

**Comment by kevincobain2000** [comment]
v2.39
