### ISSUE TITLE
[BUG] Demo app is crashing on click of response tab

### ISSUE THREAD

**Issue by hammadzafar05** [rakutentech/laravel-request-docs#385]
**Describe the bug**
The screen is crashing on clicking on response tab before sending the request

**To Reproduce**
1. Error is visible in the demo app as well (https://rakutentech.github.io/laravel-request-docs/?api=https://raw.githubusercontent.com/rakutentech/laravel-request-docs/master/ui/public/sample.json)

**Screenshots**
![image](https://github.com/user-attachments/assets/7fb13178-c614-45dd-82e9-8c3e3769fc8c)

![image](https://github.com/user-attachments/assets/370b3c4b-4887-4830-953a-94b65c4e8f68)

**Comment by kevincobain2000** [comment]
Demo app is just a static site and not hooked with a backend api. It’s for visuals.

**Comment by hammadzafar05** [comment]
Im facing the same error on my newly created laravel app as well.
