### ISSUE TITLE
Can you add Laravel 9 support?

### ISSUE THREAD

**Issue by axcherednikov** [rakutentech/laravel-request-docs#39]

**Comment by nimah79** [comment]
A commit was pushed to have Laravel 9 support (cb569fb007475e71da56f0966ff8efd172c32fcb), but the changes are not in the master branch now.

**Comment by axcherednikov** [comment]
If necessary, I can help make the right changes to the library for Laravel 9 to speed up the upgrade process.

**Comment by kevincobain2000** [comment]
Let me check

**Comment by kevincobain2000** [comment]
Sorry the commit went rougue, I have put back that diff on master, please check v1.13
