### ISSUE TITLE
[BUG] The screen crashes by clicking on the response tab of any API before sending the request.

### ISSUE THREAD

**Issue by hammadzafar05** [rakutentech/laravel-request-docs#390]
Facing this issue on a fresh laravel app.
![image](https://github.com/user-attachments/assets/5ffb760c-e6ab-4899-a0d1-2071c9b2ffba)
getting this error on console and screen blanks out

**Comment by kevincobain2000** [comment]
Hmmmm, on fresh app? Will check.

**Comment by hammadzafar05** [comment]
Yes Please

**Comment by kevincobain2000** [comment]
Pushing the latest version in 10 mins. Sorry for the inconvenience. And thanks for reporting.

**Comment by kevincobain2000** [comment]
v2.41

**Comment by hammadzafar05** [comment]
Thank you very much
