### ISSUE TITLE
Feature: Please filter by route and method.

### ISSUE THREAD

**Issue by axcherednikov** [rakutentech/laravel-request-docs#44]
I have two routes - mobile and back office. I would like them to be grouped by route name and method when filtering. It would be nice to add a separation between these methods, but I understand that this is a rare case.

```php
//RouteServiceProvider::class

$this->routes(function () {
    Route::prefix('backoffice/api/v1')
        ->middleware('backoffice.api')
        ->name('backoffice.api.v1.')
        ->namespace($this->namespace)
        ->group(base_path('routes/api/backoffice/v1.php'));
    
    Route::prefix('mobile/api/v1')
        ->middleware('mobile.api')
        ->name('mobile.api.v1.')
        ->namespace($this->namespace)
        ->group(base_path('routes/api/mobile/v1.php'));
    });
}

```

**Comment by kevincobain2000** [comment]
LeT me see what I can do

**Comment by kevincobain2000** [comment]
Before I tackle grouping, which can be complicated as different people have different opinions about how they'd like to group the API's. Current default grouping is by the HTTP METHOD.

I have added a live search feature, see if it helps you.
I ll keep this issue open for now

https://github.com/rakutentech/laravel-request-docs/pull/47/files

![Screen Shot 2022-02-15 at 21 46 35](https://user-images.githubusercontent.com/629055/154065227-c983475a-9808-4382-ab96-ea181d327278.png)
