### ISSUE TITLE
method_exist(rules) instaed instanceof FormRequest test

### ISSUE THREAD

**Issue by matteocostantini** [rakutentech/laravel-request-docs#55]
Hi,
I'm a developer for a laravel api and i want build docs with your packages.

It's more important to open the possibility to test method_exist(rules) instaed instanceof FormRequest test.

I've RequestClasses that are not inherited from FormRequest class. It's important to test parameter instance has rules() method.

**Comment by kevincobain2000** [comment]
Makes sense. Let me see what I can do. Can you provide a simple sample of your request class.

**Comment by kevincobain2000** [comment]
Thanks for the suggestion. Done in v1.17
