### ISSUE TITLE
getting 404 on request-docs

### ISSUE THREAD

**Issue by dpreiss** [rakutentech/laravel-request-docs#59]
In my dev server, everything works great, but I'm running php 7.4.   In my production servicer, we have php 8.1.3 and I'm getting 404 on /request-docs/

Could it be the php version?

**Comment by qwasyx0** [comment]
@dpreiss did you solve the issue? I have same problem in docker environment locally works and 404 on prod.

**Comment by kevincobain2000** [comment]
By default I don’t suggest it to enable it on prod without proper middleware. 
but if it is showing 404, it could be because it is installed only as a dev dependency 

`composer require rakutentech/laravel-request-docs --dev `

you could confirm your composer.json

**Comment by JunaidQadirB** [comment]
I have installed it under `require` but still get 404. 

It's development vm.

I have tried clearing cache restarting server and php-fpm but nothing works.

I can see the `request-docs` end point in the routes list.

Regards,
