### ISSUE TITLE
Feature request - JSON object structure validation

### ISSUE THREAD

**Issue by jackkitley** [rakutentech/laravel-request-docs#69]
Good morning

Just a feature request for the JSON request structure. I like the way the generation for API documentation grabs the request rules.

Would like to just see it in JSON object format.

from this:

`{
  "dealership.dealership_group_id": "",
  "company.brand_name": "",
  "company.trading_name": "",
  "company.registered_name": "",
  "company.reg_no": "",
  "company.vat_no": "",
  "company.email": "",
  "company.telephone": "",
  "company.website_url": "",
  "address.unit_no": "",
  "address.line1": "",
  "address.line2": "",
  "address.post_code": "",
  "address.province": "",
  "address.country": ""
}`

To this:

`{
   "dealership":{
      "dealership_group_id":""
   },
   "company":{
      "brand_name":"",
      "trading_name":"",
      "registered_name":"",
      "reg_no":"",
      "vat_no":"",
      "email":"",
      "telephone":"",
      "website_url":""
   },
   "address":{
      "unit_no":"",
      "line1":"",
      "line2":"",
      "post_code":"",
      "province":"",
      "country":""
   }
}`

**Comment by kevincobain2000** [comment]
I know what you mean here. This should not be hard to implement. I ll work on it.

**Comment by bmherold** [comment]
+1 To this as well! Would make playing around with requests much easier.

**Comment by SOSTheBlack** [comment]
+1 Preciso que o request validator seja traduzido para isso

**Comment by kevincobain2000** [comment]
For now at least I have added a feature that will remember your previous post body, so you don't have to keep changing the post body on page refresh.
I ll look into it as default next.

**Comment by kevincobain2000** [comment]
Done in version 2.6 https://github.com/rakutentech/laravel-request-docs/releases/tag/2.6
