### ISSUE TITLE
Missing sql queries

### ISSUE THREAD

**Issue by axcherednikov** [rakutentech/laravel-request-docs#72]
Hello! Maybe it's not an issue, but why don't I have sql displayed when querying?
![Снимок экрана 2022-05-17 в 21 35 13](https://user-images.githubusercontent.com/52137648/168886269-db9dcc53-f58e-476d-8a78-5f380629908f.png)

**Comment by kevincobain2000** [comment]
Can you check if your ``config('app.debug')`` is ON?

**Comment by axcherednikov** [comment]
> Can you check if your `config('app.debug')` is ON?

APP_ENV=production
APP_DEBUG=false

**Comment by kevincobain2000** [comment]
This tool is not supposed to be for prod, in order for the SQL query for prod (highly not recommended) the ``app.debug`` needs to be true

**Comment by axcherednikov** [comment]
> This tool is not supposed to be for prod, in order for the SQL query for prod (highly not recommended) the `app.debug` needs to be true

APP_ENV=local
APP_DEBUG=true

Also does not work.

**Comment by kevincobain2000** [comment]
Hmm can you please provide debug information if you have? I have checked and there is no problem with the library

**Comment by axcherednikov** [comment]
![Снимок экрана 2022-05-18 в 12 11 12](https://user-images.githubusercontent.com/52137648/169003601-6a3cb82f-f9ab-44ef-a9af-0d97a6dff4da.png)

I saw it in the telescope, is it possible?

**Comment by axcherednikov** [comment]
@kevincobain2000 It's ok, I haven't applied middleware to my request. Thank you for your help!

**Comment by kevincobain2000** [comment]
Cool then
