### ISSUE TITLE
Not getting a Response on LRD

### ISSUE THREAD

**Issue by ALGAzevedo** [rakutentech/laravel-request-docs#73]
Hello,

I was testing this LRD and its very simple to start, thanks for that. Unfortunately when i run the endpoints it gives me a 200 but i see no response body.
This is all i see after running the endpoint with the Bearer already filled that i have to get from PostMan because i can not get a response from the login:

![image](https://user-images.githubusercontent.com/46000644/174054987-b8fe59ad-295c-4f84-a27a-4dce2cf1a594.png)
![image](https://user-images.githubusercontent.com/46000644/174055039-c5ff54a8-4ca7-4db6-aaaa-75b1288b1b7a.png)

I am returning resources, but i tried returning only an array and it did not work.

Am I doing something wrong? This is working perfectly fine in swagger if I do the whole process of creating the annotations.

Thank you

**Comment by kevincobain2000** [comment]
Hmm, from the screenshot something is odd to me.
The URL says `:10000` while in the REQUEST URL code block it is showing up as localhost (without the port)
Is your application running on the port `:10000`?

If yes, then can you try editing the code block of REQUEST URL (it is an editable field) and re-hit it.
