### ISSUE TITLE
Read and Identity Enums

### ISSUE THREAD

**Issue by olliescase** [rakutentech/laravel-request-docs#80]
Enums are allowed as a query parameter - it would be great if it could read this and identify the possible routes based on this.

Moreover, generally identifying the data type of the route param would be great.

For example; for uuids:
`/users/{record}` => `record: string`

For autonumber ids:
`/users/{record}` => `record: integer`

Where model is an enum, record is string:
`/{model}/{record}` => `model: enum [users, projects, tasks, quotes]`

Probably displayed as a table, such as:

```
Query Params:

Field    | Type   | Data
===================================
model    | enum   | users, projects, tasks, quotes
-----------------------------------
record   | string |
-----------------------------------
```

**Comment by kevincobain2000** [comment]
Could add

**Comment by kevincobain2000** [comment]
Hmm I tried but this can't be added
