### ISSUE TITLE
Publish index.blade.php view to customize it 

### ISSUE THREAD

**Issue by RogerKeliu** [rakutentech/laravel-request-docs#81]
It's possible to publish vendor/rakutentech/laravel-request-docs/resources/views/index.blade.php in order to modify some of the html render ?

**Comment by kevincobain2000** [comment]
Yes it is possible, it can be published

**Comment by amine-y** [comment]
For anyone who is still searching you can override it by copying vendor/rakutentech/laravel-request-docs/resources/views/index.blade.php to => resources/views/vendor/request-docs/index.blade.php and it will work
