### ISSUE TITLE
Dependency Inject in Request failed to generate Docs

### ISSUE THREAD

**Issue by syahrul84** [rakutentech/laravel-request-docs#82]
In the request, I tried to inject some classes in the __construct, and when generating the API document, the rules/field is not showing. The code however is valid and working.

Laravel: 9
PHP: 8.1.9

`

    class IndexRequest extends RequestAbstract
    {
        private $userRepository;

        public function __construct(
            UserRepository $userRepository
        ) {
            $this->userRepository = $userRepository
        }

        public function rules(): array
        {
            return [
                'id' => [
                    'required', 'integer', 'min:1', 'max:100'
                ],
                'text' => [
                    'string'
                ],
            ];
        }

        protected function persist()
        {
            ...
        }
    }

`

**Comment by kevincobain2000** [comment]
Thanks for reporting. I ll have a look.

**Comment by kevincobain2000** [comment]
Are you sure it is not a syntax error issue?

```
    public function __construct(
        UserRepository $userRepository
    ) {
        $this->userRepository = $userRepository;
                                               ↑here..
    }
```

**Comment by syahrul84** [comment]
> Are you sure it is not a syntax error issue?
> 
> ```
>     public function __construct(
>         UserRepository $userRepository
>     ) {
>         $this->userRepository = $userRepository;
>                                                ↑here..
>     }
> ```

yup, I'm sure. You can try the code with the missing semicolon. The document for the rules will not be generated when there is dependency injection in the constructor

**Comment by kevincobain2000** [comment]
>You can try the code with the missing semicolon.

Do you mean with or without?
Does it fail to generate rules when there is no syntax error? Can you please fix that syntax error and try it?

**Comment by MunirBash** [comment]
Facing this issue as well. Rules are not showing for endpoints that have dependency injection.

**Comment by syahrul84** [comment]
Request file:-
![Screenshot 2022-09-12 at 11 43 57 AM](https://user-images.githubusercontent.com/45033533/189570101-0dd395ad-30ab-40b2-a0b0-9a8488086734.png)

Generated document:- 
![Screenshot 2022-09-12 at 11 44 20 AM](https://user-images.githubusercontent.com/45033533/189570124-a679e5ab-b159-4d0a-a6d4-3d567a5ab903.png)

The rules are not generated in the document.

**Comment by kevincobain2000** [comment]
Thanks, I ll have a look

**Comment by kevincobain2000** [comment]
I think I have found where the issue was, I have pushed the new tag 1.24, please update and re-try.
#84 
Thanks for reporting

**Comment by MunirBash** [comment]
Issue is fixed, thanks @kevincobain2000
