### ISSUE TITLE
/api/* routes not included in generated docs

### ISSUE THREAD

**Issue by nathangoss** [rakutentech/laravel-request-docs#85]
Hi All,

Is there any reason why my /api/* routes are not getting included in the generated documents?

They are available when I run `php artisan route:list` but not in the LRD docs.

Any ideas?

Thanks!

Nathan

**Comment by kevincobain2000** [comment]
https://github.com/rakutentech/laravel-request-docs/blob/master/config/request-docs.php#L6

Turn this to `true` and find out if there are any errors on the page that is making it not show up.

**Comment by nathangoss** [comment]
`Call to a member function get() on null`

The line starting with device_id is the line throwing the error:


```
public function rules()
{
        // dd($this);

        return [
            'device_id' => ['required', 'string', 'unique:App\Models\ScannerDevice,device_id,'.$this->device->id],
            'location' => ['required', 'string'],
        ];
    }
```

This is not an api/ route, and when setting Debug to false, the route related to the above is generated just fine.

**Comment by kevincobain2000** [comment]
Follow this: https://github.com/rakutentech/laravel-request-docs/issues/83#issuecomment-1242737419

**Comment by kevincobain2000** [comment]
>Is there any reason why my /api/* routes are not getting included in the generated documents?

By default `/api/*` routes are not in the exclude pattern, the only explanation is that there is an object there that is throwing errors making the library not able to parse the rules.

**Comment by nathangoss** [comment]
> Follow this: [#83 (comment)](https://github.com/rakutentech/laravel-request-docs/issues/83#issuecomment-1242737419)

I've had a look at this comment, and have tried what is suggested, however the behaviour is not changed at all.
