### ISSUE TITLE
I there any way to update design or custom filter or change text?

### ISSUE THREAD

**Issue by cdmathukiya** [rakutentech/laravel-request-docs#86]
Hi @kevincobain2000,

I have setup this package and working fine.
But i need to customize filter and some label changes i am trying to update index.html but is is not affected.

Is there any way to cuatomize design, label or search filter?

I am not sure that index.html file is using or not 

Thank you

**Comment by kevincobain2000** [comment]
Yes there is a way. You can do vendor:publish and update the blade file

**Comment by cdmathukiya** [comment]
Thank you @kevincobain2000 
I got it
