### ISSUE TITLE
Can not export to postman

### ISSUE THREAD

**Issue by vncdn** [rakutentech/laravel-request-docs#89]
Please support me can export for postman in laravel 9

**Comment by kevincobain2000** [comment]
Hmm it should be able to. What is the error that you have?

**Comment by vncdn** [comment]
> Hmm it should be able to. What is the error that you have?

Oh! maybe cache. It's work normally. Thank you so much.

**Comment by kevincobain2000** [comment]
Cool. Good to hear.
