### ISSUE TITLE
Feature request: Sorting routes in generated HTML

### ISSUE THREAD

**Issue by FranBdcm** [rakutentech/laravel-request-docs#9]
Hello!

I am testing your package with some Laravel projects and I have a question for the generated route list. For now, I am using a random Laravel with default config of your package.

In my generated HTML, the routes are sorted by their method. Is it possible to sort them by name/prefix, or I am doing something wrong?

Thanks!

**Comment by kevincobain2000** [comment]
Hi,
Right now the sorting is done in a closed box, which is by groups of ``GET|POST|..`` by the method.
https://github.com/rakutentech/laravel-request-docs/blob/10c7f45ce615d66d3816c28e9d3f6558f806a86f/src/LaravelRequestDocs.php#L35

Let me consider about sorting by ``name/prefix`` on what can be done and will push in the next version.

Hopefully, 2 weeks.

**Comment by kevincobain2000** [comment]
Done by #12
