### ISSUE TITLE
Max width left sidebar

### ISSUE THREAD

**Issue by PiekarskiKarol** [rakutentech/laravel-request-docs#94]
Hi!
Thanks for this package! This is great - Great job! I have a suggestion for the left sidebar. When I add X-CSRF-TOKEN, I have this sidebar on 50% of the entire page. Can you add max-width: 300 / 400px or in configuration max-width as parameter?

**Comment by kevincobain2000** [comment]
Yea. I am sorry I have a bad sense for web design. I ll see what I can do. Should be a quick fix. Over the weekends!

**Comment by PiekarskiKarol** [comment]
No worries! What you did is amazing! I see that you are working on tailwind - to `#app aside` you can add class `max-w-sm` and it will solve my problem
